### ISSUE TITLE
Erreur de commande WINRM lors de la création du premier DC Kingslanding

### ISSUE THREAD

**Issue by KoalaWSMTW** [Orange-Cyberdefense/GOAD#1]
Impossible de lancer l'infrastructure avec la commande vagrant up

![image](https://user-images.githubusercontent.com/49360560/142466088-6fb4e205-0b49-43bf-a86c-31b533ce5da0.png)

Auriez vous une piste concernant la résolution de cette erreur ? :)

**Comment by KoalaWSMTW** [comment]
Environnement : 

J’essaie de faire tourner GOAD dans une VM Ubuntu virtualisée sur un ESXi..

-----------------------
Ubuntu 20.04.3 LTS
VirtualBox 6.1.26
Vagrant 2.2.6
-----------------------

**Comment by Mayfly277** [comment]
Seems to be the same error on guest addition :  https://github.com/Orange-Cyberdefense/GOAD/issues/2
