### ISSUE TITLE
Ansible error child_domain (enable the Ethernet 2 interface (local) for DNS client requests)

### ISSUE THREAD

**Issue by 7h3w4lk3r** [Orange-Cyberdefense/GOAD#107]
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/61451071/c69bb8d9-723d-4bc3-87bb-8d6f66029d0c)

i get this error while configuring the child domain.

**Comment by tx1ee** [comment]
Hey bro, did you solve this problem? I have the same problem

**Comment by 7h3w4lk3r** [comment]
> Hey bro, did you solve this problem? I have the same problem

nope :(

**Comment by N1etzsche0** [comment]
I encountered the same problem in my archlinux, refer to [deploy-goad](https://github.com/lkarlslund/deploy-goad), try to rebuild on Ubuntu 22.04.2 LTS, and it works.

**Comment by 7h3w4lk3r** [comment]
> I encountered the same problem in my archlinux, refer to [deploy-goad](https://github.com/lkarlslund/deploy-goad), try to rebuild on Ubuntu 22.04.2 LTS, and it works.
unfortunately i cant change my host OS and i dont think it has anything to do with that. looks like a vbox issue to me. i removed the Ansible commands related to network interface activation/deactivation but then the machine could not  join the domain at all.

**Comment by CodeXTF2** [comment]
bump, same issue. has anyone solved it? (running on windows from an ubuntu vm)

**Comment by HardcoreMang0** [comment]
Same issue here any fix?

**Comment by laztname** [comment]
I change content on file :
ansible/roles/common/tasks/main.yml
ansible/roles/child_domain/tasks/main.yml
ansible/roles/member_server/tasks/main.yml

changes
---
- adapter_names: "{{domain_adapter}}"
+ adapter_names: "Ethernet 2"
---

I thinks it's work well

deployed GOAD to proxmox instance with instruction from https://mayfly277.github.io/posts/GOAD-on-proxmox-part4-ansible/

**Comment by 7h3w4lk3r** [comment]
> I change content on file : ansible/roles/common/tasks/main.yml ansible/roles/child_domain/tasks/main.yml ansible/roles/member_server/tasks/main.yml
> 
> changes
> 
> ```
> ---
> - adapter_names: "{{domain_adapter}}"
> + adapter_names: "Ethernet 2"
> ---
> ```
> 
> I thinks it's work well
> 
> deployed GOAD to proxmox instance with instruction from https://mayfly277.github.io/posts/GOAD-on-proxmox-part4-ansible/

can anyone confirm this ? i dont have the LAB anymore.

**Comment by jamu85** [comment]
I have had the same error. During the cloud init process the e1000 device is created as ethernet 2 while a hidden virtio interface was in the device manager as ethernet 1. I had to delete the hidden virtio ethernet device by hand and rename the e1000 device in order to make the ansible playbook run. I first thought, it was related to the bpg/proxmox provider that i use for compatablity reasons on proxmox 8 but most probably it's a cloudbase behaviour causing this issue.

**Comment by Mayfly277** [comment]
if you get that kind of error the adapter name is not corresponding to the one in the vm.
change the adapter name in : ad/GOAD/providers/proxmox/inventory
lines nat_adapter and domain_adapter to the adapter name you get.
and then relaunch the install :)
