### ISSUE TITLE
Issue running vagrant up

### ISSUE THREAD

**Issue by JitBox** [Orange-Cyberdefense/GOAD#108]
When I run Vagrant up I get this error:

'''
xii@Box:/opt/GOAD$ vagrant up
Bringing machine 'DC01' up with 'vmware_desktop' provider...
Bringing machine 'DC02' up with 'vmware_desktop' provider...
Bringing machine 'DC03' up with 'vmware_desktop' provider...
Bringing machine 'SRV02' up with 'vmware_desktop' provider...
Bringing machine 'SRV03' up with 'vmware_desktop' provider...
==> DC01: Cloning VMware VM: 'StefanScherer/windows_2019'. This can take some time...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "snapshot", "/home/xii/.vagrant.d/boxes/StefanScherer-VAGRANTSLASH-windows_2019/2021.05.15/vmware_desktop/WindowsServer2019.vmx", "9d98a1f7-6031-4c87-9428-e884730e3291", {:notify=>[:stdout, :stderr]}]

Stdout: Error: The operation is not supported

Stderr: 
'''

I followed the instructions to a tee, not sure what the issue is and how to resolve.

**Comment by warthogtk** [comment]
Same issue here

**Comment by warthogtk** [comment]
Not the best way probably but as I have VMWare Workstation Pro I changed 

`~/.vagrant.d/gems/3.0.5/gems/vagrant-vmware-desktop-3.0.2/lib/vagrant-vmware-desktop/driver/base.rb`

line 1288 : 
`cmd = ["-T", product_type] + command`
to 
`cmd = ["-T", "ws"] + command`

A bit dirty .. but it works ;)

**Comment by Mayfly277** [comment]
reference to this issue : https://github.com/hashicorp/vagrant-vmware-desktop/pull/32#issuecomment-1236090788
solution: change vagrant version or patch by hand
