### ISSUE TITLE
proxmox Build error resolution

### ISSUE THREAD

**Issue by tx1ee** [Orange-Cyberdefense/GOAD#109]
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/28696494/df5a1748-6cd8-49ce-a7d1-d076e56dcebf)

==> proxmox-iso.windows: Error creating VM: error creating VM: unable to create VM 153 - unsupported format 'qcow2' at /usr/share/perl5/PVE/Storage/ZFSPoolPlugin.pm line 238., error status:  (params: map[agent:1 args: boot: cores:2 cpu:kvm64 description:Packer ephemeral build VM hotplug: ide2:local:iso/windows_server_2019_17763.737_eval_x64.iso,media=cdrom kvm:true machine: memory:4096 name:WinServer2019x64-cloudinit net0:virtio=7E:10:A8:03:85:44,bridge=vmbr3,tag=10,firewall=false onboot:false ostype:win10 pool:GOAD sata0:disk2:40,format=qcow2 scsihw:lsi sockets:1 startup: tags: vmid:153])
Build 'proxmox-iso.windows' errored after 2 seconds 159 milliseconds: Error creating VM: error creating VM: unable to create VM 153 - unsupported format 'qcow2' at /usr/share/perl5/PVE/Storage/ZFSPoolPlugin.pm line 238., error status:  (params: map[agent:1 args: boot: cores:2 cpu:kvm64 description:Packer ephemeral build VM hotplug: ide2:local:iso/windows_server_2019_17763.737_eval_x64.iso,media=cdrom kvm:true machine: memory:4096 name:WinServer2019x64-cloudinit net0:virtio=7E:10:A8:03:85:44,bridge=vmbr3,tag=10,firewall=false onboot:false ostype:win10 pool:GOAD sata0:disk2:40,format=qcow2 scsihw:lsi sockets:1 startup: tags: vmid:153])

Modify qcow2 in the packer.json.pkr.hcl file to raw

Solution ideas

https://github.com/hashicorp/packer-plugin-proxmox/issues/92

**Comment by grumo35** [comment]
Are you using a local lvm on proxmox ?

**Comment by AkechiShiro** [comment]
@tx1ee You need to use a directory with ext4, ZFS can be used but the setup is complex.

Basically, all block filesystem are a no go for qcow2, only file level can be used, see

You can close this issue, I believe more information is here : https://forum.proxmox.com/threads/no-qcow2-on-zfs.37518/

**Comment by Mayfly277** [comment]
if your proxmox doesn't support qcow2 you can now change the disk_format to raw in the configuration file.
