### ISSUE TITLE
Issue with Synchronizing the Domains

### ISSUE THREAD

**Issue by ahnospell44** [Orange-Cyberdefense/GOAD#114]
When getting to the "groups_domains : synchronizes all domains]" step, the dc02 system appears to be having issues and never returns. Does anyone have a way around this? 
I've rebooted the system several times, when this happens and it never opens back up. 
This is Oracle VirtualBox and I am using the "ansible-galaxy main.yml --limit=dc02" just to get the system to try to set up on its own. 
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/7912525/c4bb69cd-cdbb-4279-9e9b-2f91efcc6f25)

**Comment by Mayfly277** [comment]
this should be due to a trust issue due to parallel task.
if you recreate the lab this should be fix by this : https://github.com/Orange-Cyberdefense/GOAD/blob/3436b9702b5b9cb6c52c47f3ae1fd582326da921/ansible/ad-trusts.yml#L23

if not delete the trust on the two dc and relaunch the playbook
