### ISSUE TITLE
Fail to configure password properties

### ISSUE THREAD

**Issue by necx512** [Orange-Cyberdefense/GOAD#115]
Hello,

I tried to install GOADv2 through the standard instructions:

```
# providing (create and start the vms)
vagrant up
# provisioning (setup the goad config and install inside the vms)
sudo docker build -t goadansible .
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook -i ../ad/sevenkingdoms.local/inventory main.yml
```

However, I got the following error related to password properties:
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/01026c1e-1142-4187-8c1c-cc97f0967993)

--
I'm using Archlinux. 32GB of memory. A 220GB disk. AMD Ryzen 7 3700X 8-Core Processor.

Any ideas?

**Comment by necx512** [comment]
I don't know if it is important but I notices that the ordered of the playbook in the yaml file is not the same that the one given in the README.md.

Readme.me:
```
ansible-playbook build.yml        # Install stuff and prepare vm
ansible-playbook ad-servers.yml   # create main domains, child domain and enroll servers
ansible-playbook ad-trusts.yml    # create the trust relationships
ansible-playbook ad-data.yml      # import the ad datas : users/groups...
ansible-playbook servers.yml      # Install IIS and MSSQL
ansible-playbook ad-relations.yml # set the rights and the group domains relations
ansible-playbook adcs.yml         # Install ADCS on essos
ansible-playbook ad-acl.yml       # set the ACE/ACL
ansible-playbook security.yml     # Configure some securities (adjust av enable/disable)
ansible-playbook vulns.yml        # Configure some vulnerabilities
```

main.yml:
```
- import_playbook: build.yml
- import_playbook: ad-servers.yml
- import_playbook: ad-trusts.yml
- import_playbook: ad-data.yml
- import_playbook: laps.yml
- import_playbook: ad-relations.yml
- import_playbook: adcs.yml
- import_playbook: ad-acl.yml
- import_playbook: servers.yml
- import_playbook: security.yml
- import_playbook: vulnerabilities.yml
```

**Comment by necx512** [comment]
I have done some investigations on this issue.

This error is related to the module `win_ad_object` that is executed on the task `Configure Password Properties` (file ansible/roles/laps/dc/tasks/install.yml).

Basically, if the AD object `ms-Mcs-AdmPwd` does not exist, the script `win_ad_object.ps1` try to create it by the cmdlet `New-ADObject`, and this cmdlet create the error.

I have executed the script `win_ad_object.ps1` manually on DC02 (after having fixed some variables) oin order to reproduce the error:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/1f6e8c68-a582-4afa-ba99-ab6c71bc560f)

At this moment, it seems that `ms-Mcs-AdmPwd` is missing :

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/cb793c1e-dd4b-47fc-b860-2a5c1742b5d3)

However, by waiting about 45 minutes, this value appears:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/2c9fc614-33e2-4914-bdd3-2f89b91c083d)

And then, by replaying the playbook laps.yml all works well.

I have this issue only on DC02 (the child domain). I'm wondering if a synchronisation mechanism with the parent domain is performed. Please feel free to explain.

**Comment by Mayfly277** [comment]
This is a synchronisation delay in the vm. if you find a way to fix this on playbook please do a PR.
by now just rerun the playbook, sorry i doesn't have a better solution ^^
