### ISSUE TITLE
TASK [laps/dc : Ensure GPO is Linked] : The specified domain either does not exist or could not be contacted.

### ISSUE THREAD

**Issue by necx512** [Orange-Cyberdefense/GOAD#117]
Hello,

I try to install GOADv2 step by step:

```
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook build.yml
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook ad-servers.yml
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook ad-trusts.yml
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook ad-data.yml
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook laps.yml
```

I encounter an issue with the playbook laps.yml:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/56ff97eb-afa7-4070-a3fb-77dd00e0bf93)

What do you think?

**Comment by necx512** [comment]
It seems that disabling IPv6 on DC02 (on the interface that is configured to use DHCP to get IPv6) makes it work

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/d09933e0-2230-4ceb-928a-8fa42ab8f32b)

Do you know why?

**Comment by hexagram-sec** [comment]
I also encountered the same problem. The network has been modified according to the diagram, but it has not been resolved.

**Comment by HarunYasin** [comment]
Hi, could anyone solve this issue? Thanks in advance!

**Comment by necx512** [comment]
@HarunYasin @hexagram-sec : What is your operating system? 

The issues I encounter is when I try to deploy GOAD on ArchLinux. I am maybe wrong but I believe this is because GOAD is not expected to be deployed on the most recent softwares and dependancies that is installed by the ArchLinux package managers.

I don't have such error on Ubuntu 22.04.3 LTS. Note however that I used a pre-release of vagrant to make it work : https://github.com/hashicorp/vagrant/releases/tag/2.3.8.dev%2B000032-f72cda8b. This is due to this issue: https://github.com/hashicorp/vagrant/issues/13076

**Comment by necx512** [comment]
@HarunYasin @hexagram-sec : What is your operating system?

The issues I encounter is when I try to deploy GOAD on ArchLinux. I am maybe wrong but I believe this is because GOAD is not expected to be deployed on the most recent softwares and dependancies that is installed by the ArchLinux package managers.

I don't have such error on Ubuntu 22.04.3 LTS. Note however that I used a pre-release of vagrant to make it work : https://github.com/hashicorp/vagrant/releases/tag/2.3.8.dev%2B000032-f72cda8b. This is due to this issue: https://github.com/hashicorp/vagrant/issues/13076

**Comment by Fu1lMetal** [comment]
actually vagrant version doesn't matter,it still not work,my environment is widnows10

**Comment by Fu1lMetal** [comment]
> 似乎在 DC02 上禁用 IPv6（在配置为使用 DHCP 获取 IPv6 的接口上）可以使其工作
> 
> ![图像](https://user-images.githubusercontent.com/82725933/255247702-d09933e0-2230-4ceb-928a-8fa42ab8f32b.png)
> 
> 你知道为什么吗？

dhcp will change the origin ip

**Comment by n0nam34m3** [comment]
Add just before 'Ensure GPO is Linked' task in ansible/roles/laps/dc/tasks/install

- name: Disable IPv6 on Windows 10
  ansible.windows.win_regedit:
    path: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
    name: 'DisabledComponents'
    data: 0xffffffff
    type: dword
  register: ipv6_disable_result

- name: Reboot to apply IPv6 changes
  ansible.windows.win_reboot:
  when: ipv6_disable_result.changed
