### ISSUE TITLE
ad-relations.yml The server has rejected the client credential

### ISSUE THREAD

**Issue by necx512** [Orange-Cyberdefense/GOAD#118]
After the execution of the playbooks build.yml, ad-servers.yml, ad-trusts.yml, ad-data.yml and laps.yml, I got an error while playing ad-relations.yml:

```
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook ad-relations.yml
```
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/eb0eee89-4b1c-4c3d-8c3c-119ab1c214c0)

The task that is responsible for this issue is located in the file  `ansible/roles/groups_domains/tasks/main.yml`:
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/3992b2dc-6393-421f-a149-0e7df44759c4)

This task uses a module that can be found here: 
https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_group_membership.ps1. 
From it, I have reproduced the issue with a small amount of code:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/82725933/157b6e73-708c-4aa5-b420-6eade576c5af)

For some reasons, the domain in the variable $domain_username (north.sevenkingdoms.local) is ignored and Get-ADObject try to authenticate with the Administrator account that is registered on DC03 (essos domain).

Do you have any workaround?
Thank you

**Comment by Mayfly277** [comment]
This error should not append anymore. This was due to parallel creation of the external trust relation, depending on your system could be done nicely or with error. This task is no more done in parallel and you should not have this error anymore.
please re-run you playbook if it happend. if it is not solving please reopen this issue.
