### ISSUE TITLE
installation error network

### ISSUE THREAD

**Issue by cybertuxh4xor** [Orange-Cyberdefense/GOAD#122]
when I goto run this command
"sudo docker build -t goadansible ."
I get this.

kali@kali:/opt/GOAD$ sudo docker build -t goadansible .
Sending build context to Docker daemon  37.28MB
Step 1/8 : FROM ubuntu:22.04
Get "https://registry-1.docker.io/v2/library/ubuntu/manifests/sha256:aabed3296a3d45cede1dc866a24476c4d7e093aa806263c27ddaadbdce3c1054": dial tcp [2600:1f18:2148:bc01:c4:4967:28eb:1824]:443: connect: network is unreachable

**Comment by Mayfly277** [comment]
This seems to be a network issue and not related to the project.
