### ISSUE TITLE
packer-provisioner-powershell plugin couldn't create elevated shell

### ISSUE THREAD

**Issue by Xp101T7** [Orange-Cyberdefense/GOAD#123]
I'm able to get connection to winRM for the life of me cant figure out what to modify the create shell snippet of code. Any ideas on how to modify scripts to get this elevate properly? or maybe a fixed version of a script if you know the solution...

I have searched for references on ansible, packer and nothing is seeming to work from online suggested fixes. I dont want to cancel anything out that I tried bc im learning packer and ansible still here. HALP... 

==> proxmox-iso.windows: Provisioning with powershell script: ./scripts/sysprep/cloudbase-init.ps1
2023/09/23 22:56:54 packer-provisioner-powershell plugin: Opening ./scripts/sysprep/cloudbase-init.ps1 for reading
2023/09/23 22:56:54 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1
2023/09/23 22:56:54 packer-provisioner-powershell plugin: [INFO] 101 bytes written for 'uploadData'
2023/09/23 22:56:54 [INFO] 101 bytes written for 'uploadData'
2023/09/23 22:56:54 packer-plugin-proxmox_v1.1.3_x5.0_linux_amd64 plugin: 2023/09/23 22:56:54 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1'
2023/09/23 22:56:57 packer-provisioner-powershell plugin: Retryable error: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-6b231fb4-f115-4d8e-68bd-a9f08ef6d8fe.tmp: Couldn't create shell: unknown error Post "https://192.168.10.109:5986/wsman": dial tcp 192.168.10.109:5986: connect: no route to host
2023/09/23 22:56:59 packer-provisioner-powershell plugin: [INFO] 0 bytes written for 'uploadData'
2023/09/23 22:56:59 [INFO] 0 bytes written for 'uploadData'
2023/09/23 22:56:59 packer-plugin-proxmox_v1.1.3_x5.0_linux_amd64 plugin: 2023/09/23 22:56:59 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1'
2023/09/23 22:57:06 packer-provisioner-powershell plugin: Building elevated command wrapper for: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1; &'c:/Windows/Temp/script-650f6d36-cd3f-99d9-6096-14f269e178c1.ps1'; exit $LastExitCode }"
2023/09/23 22:57:06 packer-provisioner-powershell plugin: Command [powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1; &'c:/Windows/Temp/script-650f6d36-cd3f-99d9-6096-14f269e178c1.ps1'; exit $LastExitCode }" > %SYSTEMROOT%/Temp/packer-650f6d42-c5f8-45ad-6403-b56898702280.out 2>&1] converted to [powershell -executionpolicy bypass &#34;&amp; { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value &#39;SilentlyContinue&#39;};. c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1; &amp;&#39;c:/Windows/Temp/script-650f6d36-cd3f-99d9-6096-14f269e178c1.ps1&#39;; exit $LastExitCode }&#34; &gt; %SYSTEMROOT%/Temp/packer-650f6d42-c5f8-45ad-6403-b56898702280.out 2&gt;&amp;1] for use in XML string
2023/09/23 22:57:06 packer-provisioner-powershell plugin: Uploading elevated shell wrapper for command [powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-650f6d36-8ac5-938e-f811-385d7fada443.ps1; &'c:/Windows/Temp/script-650f6d36-cd3f-99d9-6096-14f269e178c1.ps1'; exit $LastExitCode }" > %SYSTEMROOT%/Temp/packer-650f6d42-c5f8-45ad-6403-b56898702280.out 2>&1] to [C:/Windows/Temp/packer-elevated-shell-650f6d42-0410-2d30-c3dd-e91ce500ae9a.ps1]
2023/09/23 22:57:06 packer-provisioner-powershell plugin: [INFO] 3499 bytes written for 'uploadData'
2023/09/23 22:57:06 [INFO] 3499 bytes written for 'uploadData'
2023/09/23 22:57:06 packer-plugin-proxmox_v1.1.3_x5.0_linux_amd64 plugin: 2023/09/23 22:57:06 Uploading file to 'C:/Windows/Temp/packer-elevated-shell-650f6d42-0410-2d30-c3dd-e91ce500ae9a.ps1'
2023/09/23 22:57:09 [INFO] (telemetry) ending powershell

**Comment by Xp101T7** [comment]
If this is no route to host why is proxmox authenticating to WinRM initially and failing here at this step?

**Comment by Mayfly277** [comment]
don't know. did you found the solution ?

**Comment by Cyb3rDudu** [comment]
@Mayfly277 I stumbled over the same issue with v3.
It failed around 10 times.
```
proxmox-iso.windows: output will be in this color.

==> proxmox-iso.windows: Retrieving ISO
==> proxmox-iso.windows: Trying ./iso/Autounattend_winserver2019_cloudinit.iso
==> proxmox-iso.windows: Trying ./iso/Autounattend_winserver2019_cloudinit.iso?checksum=sha256%3A3f56099b4f8cde99605338d7449bafaf57f59c3af16e67f3bc990e484302b160
==> proxmox-iso.windows: ./iso/Autounattend_winserver2019_cloudinit.iso?checksum=sha256%3A3f56099b4f8cde99605338d7449bafaf57f59c3af16e67f3bc990e484302b160 => /Users/dudu/Code/GOAD/packer/proxmox/iso/Autounattend_winserver2019_cloudinit.iso
    proxmox-iso.windows: Uploaded ISO to local:iso/Autounattend_winserver2019_cloudinit.iso
==> proxmox-iso.windows: Creating VM
==> proxmox-iso.windows: Starting VM
==> proxmox-iso.windows: Waiting for WinRM to become available...
    proxmox-iso.windows: WinRM connected.
==> proxmox-iso.windows: Connected to WinRM!
==> proxmox-iso.windows: Provisioning with Powershell...
==> proxmox-iso.windows: Provisioning with powershell script: ./scripts/sysprep/cloudbase-init.ps1
    proxmox-iso.windows: Windows PowerShell
    proxmox-iso.windows: Copyright (C) Microsoft Corporation. All rights reserved.
    proxmox-iso.windows:
==> proxmox-iso.windows: The argument 'C:/Windows/Temp/packer-elevated-shell-67583393-94f6-4abd-6ac6-dce78af26c2c.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
==> proxmox-iso.windows: Provisioning step had errors: Running the cleanup provisioner, if present...
==> proxmox-iso.windows: Stopping VM
==> proxmox-iso.windows: Deleting VM
Build 'proxmox-iso.windows' errored after 3 minutes 40 seconds: Script exited with non-zero exit status: 4294770688. Allowed exit codes are: [0]

==> Wait completed after 3 minutes 40 seconds

==> Some builds didn't complete successfully and had errors:
--> proxmox-iso.windows: Script exited with non-zero exit status: 4294770688. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```
After that I decided, to create the updated one which finished on the first approach.
I gave the former one without updates a second chance and it buildt.

No idea what caused it but it's still a topic with the current packer setup.
If I can anyhow help let me know how I can help debugging the issue.
