### ISSUE TITLE
Failed   Play task ../ad/sevenkingdoms.local/scripts/rdp_scheduler.ps1 

### ISSUE THREAD

**Issue by braaqwesi** [Orange-Cyberdefense/GOAD#127]
TASK [ps : Play task ../ad/sevenkingdoms.local/scripts/rdp_scheduler.ps1] *************************************************************************************************
changed: [dc02]

PLAY RECAP ****************************************************************************************************************************************************************
dc01                       : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
dc02                       : ok=14   changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
dc03                       : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
srv02                      : ok=10   changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
srv03                      : ok=10   changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by grumo35** [comment]
Hello,

Can you please rerun the playbooks with verbose options ? -v -vv -vvv ?

**Comment by Mayfly277** [comment]
does a re-run fix the problem ?
