### ISSUE TITLE
Multiple errors during setup

### ISSUE THREAD

**Issue by Andreddi** [Orange-Cyberdefense/GOAD#128]
After many hours of troubleshooting, and a couple of complete restarts, I finally succeeded in setting up this lab. Some of the errors I have ran into during setup are confusing me however, as they seem to be more about the configuration being set in the playbooks, rather than being something going wrong on my end. 
So I wanna hear if these problems are things that are to be expected during setup, and if others have run into the same things. 

I build the lab in VMware workstation, on a windows host, and I ran the playbooks from a Linux VM.

Here is a short list of problems and solutions, during the setup that ended up succeeding for me.

# Problem 1
## Description
When running the playbooks, after setting the hostname of the machines they are all restarted. All except DC03 started without trouble. DC03 had a Blue Screen of Death, with the error 0x0000142. No matter what I did, it was stuck in a loop of Blue Screen of Death.

## Solution
I deleted the entire lab, and ran everything again, as I could not get DC03 back up. It could’ve maybe been enough to just remove DC03 and run vagrant again, but I was afraid something went wrong during the download of the images. 

# Problem 2
## Description
Something relating to setting up MySQL failed on SRV02.

## Solution
Uninstall everything relating to SQL, and the directory C:\Program Files\Microsoft SQL Server, then reboot.

# Problem 3
## Description
DC03 trying to access NIC "Ethernet0" with index 4, but the index is something else, so it fails.

## Solution
Log into the VM and run the command manually. I’m not sure how this worked, or why the NIC index is not 4 from the start, since it can’t be changed.

# Problem 4
## Description
DC02 can’t resolve the name essos.local.

## Solution
I spent quite some time troubleshooting DNS to find the solution to this problem. The solution ended up being to check the forwarders for DC02, and make sure that the 192.158.56.10 forwarder is the first one. By default, the first forwarder was one in the 192.156.235.0/24 network. 

# Problem 5
## Description
Can’t RDP to DC03. It said the problem could be related to CredSSp encryption oracle remediation.

## Solution
Disable NLA in for RDP on DC03.
https://www.layerstack.com/resources/tutorials/How-to-resolve-RDP-authentication-error-due-to-the-CredSSP-encryption-oracle-remediation-on-Windows-OS

<br><br>

Especially problem 4 and 5 seems to be things that are just configured wrong in the playbooks, but I’m curious if others have run into similar problems, when setting up their lab.

Additionally, are there some tests I can run, to make sure the lab is set up correctly, since I’m afraid some things could still be configured incorrectly?

**Comment by grumo35** [comment]
Hello, 

I indeed have run into some of your issues, keep in mind that this is mostly a community driven project since you dont have to pay for anything.

The MSSQL setup on SRV02 is faulty some times.

Thanks for listing the problems, i'll try to take a look !

**Comment by Mayfly277** [comment]
problem 1 weird, trash and recreate is the good solution here, because something totaly mess on your dc03 here 
problem 2 i should add it to troubleshoot
problem 3 the index shouldn't have change this index is setup as the beginning of the install and as no reason to have change
problem 4 should be solved since i changed some steps in the lab provisionning.
problem 5 first time i see that thanks

i close and i will add some points on troubleshoot, thank you :)
