### ISSUE TITLE
ESXI support

### ISSUE THREAD

**Issue by Bladetuab** [Orange-Cyberdefense/GOAD#136]
How can I run this lab on ESXI 7??

**Comment by nobox910** [comment]
Install single VM **Ubuntu Desktop 22** on ESXi , then let deploy GOAD on VM
Deployment is completed successfully after days.
Ref: https://github.com/Orange-Cyberdefense/GOAD/blob/main/docs/install_with_virtualbox.md

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/58721688/ba701f8f-869d-4866-a36a-128c4a279209)

**Comment by Mayfly277** [comment]
nested virtualisation is not ideal but this could be done like this sure :)
also maybe a full esxi install will come one day but not for now sorry.
