### ISSUE TITLE
Ansible error: SRV02 (castelblack) failed to join domain 'north.sevenkingdoms.local'

### ISSUE THREAD

**Issue by ctixsystems** [Orange-Cyberdefense/GOAD#14]
Thanks for creating such a wonderful lab. Environment configured and working well except for this one error:

`TASK [member_server : Add member server] ************************************************
ok: [192.168.56.23]
fatal: [192.168.56.22]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local' from its current workgroup 'WORKGROUP' with following error message: The specified network name is no longer available.", "reboot_required": false}`

**System details:**

`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic`

`$ vagrant --version
Vagrant 2.2.19`

`$ vboxmanage --version
6.1.34r150636`

`$ ansible --version
ansible [core 2.12.6]
  config file = /home/user/GOAD/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/GOAD/ansible/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/GOAD/ansible/.venv/bin/ansible
  python version = 3.8.0 (default, Dec  9 2021, 17:53:27) [GCC 8.4.0]
  jinja version = 3.1.2
  libyaml = True`

Happy to provide whatever extra information might be required to investigate and resolve.

**Comment by Mayfly277** [comment]
Thx :)
Ok this is a weird error, can you try to reboot the vms and relaunch a provisioning ?

```
vagrant reload
cd ansible
ansible-playbook main.yml
```

The ansible playbook are all made to be played multiple time, if you get an issue you can try to replay the main playbook. (it will take less time as a lot of actions are already done).
castelblack and braavos are playing windows update which can take several time, maybe the servers are applying updates and are not joignable during this time.
 
If the error persist you could also remove castelblack and recreate it (`vagrant remove SRV02`, `vagrant up SRV02`) and replay the main.yml playbook.

Let me know if you solve the problem and what solution did you use.

**Comment by ctixsystems** [comment]
To correct this I ended up calling vagrant destroy and rebuilding the full environment and re-running the playbooks.

I had tried a more surgical approach with SRV02 and DC02 but that did not work.

Appreciate your response and support.
