### ISSUE TITLE
An error occurred executing a remote WinRM command - MacOS

### ISSUE THREAD

**Issue by braaqwesi** [Orange-Cyberdefense/GOAD#141]
Mac OS Monterey 
![Screen Shot 2023-11-16 at 1 51 17 pm](https://github.com/Orange-Cyberdefense/GOAD/assets/53085292/fca5a263-e4d7-4a08-8ebc-cb84449989e9)

❯ vagrant -v
Vagrant 2.4.0

**-->> ISSUE**
❯ vagrant up
An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error

**--->> SOLUTION**
Downgrade vagrant and virtualbox
Vagrant 2.2.18
❯ vagrant up
==> GOAD-DC01: Running provisioner: shell...
    GOAD-DC01: Running: ../../../../vagrant/ConfigureRemotingForAnsible.ps1 as C:\tmp\vagrant-shell.ps1
    GOAD-DC01: Self-signed SSL certificate generated; thumbprint: 204C94CD2A61772818B8C66C160A3B257FE78B43

Problem solved

**Comment by Mayfly277** [comment]
thx for this informations !
