### ISSUE TITLE
fatal: [dc03]: FAILED! => {"changed": false, "msg": "The DnsServer module failed to load properly

### ISSUE THREAD

**Issue by braaqwesi** [Orange-Cyberdefense/GOAD#144]
What could be wrong here and how do i solve this

TASK [dns_conditional_forwarder : Add dns server zone] ******************************************************************************************************************************************************************************
fatal: [dc03]: FAILED! => {"changed": false, "msg": "The DnsServer module failed to load properly: The specified module 'DnsServer' was not loaded because no valid module file was found in any module directory."}
fatal: [dc01]: FAILED! => {"changed": false, "msg": "The DnsServer module failed to load properly: The specified module 'DnsServer' was not loaded because no valid module file was found in any module directory."}

PLAY RECAP **************************************************************************************************************************************************************************************************************************
dc01                       : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
dc02                       : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
dc03                       : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
srv02                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
srv03                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by Mayfly277** [comment]
oO no idea. does a reboot and retry change anything ?

**Comment by DrorDvash** [comment]
same error for me. reboot did not work.
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/8413651/cb578451-9747-4211-8c66-04dbe0ad7567)

**Comment by 0xBang9** [comment]
To fix this error open up the VM for DC01 and DC03 then open Server Manager and then with Add Roles and Features from the Manage menu (you will find the tools on the feature list) you can get DNS Server UNDER SERVER ROLES. The DNS Server tools includes and installs DNS PowerShell module.

**Comment by Mayfly277** [comment]
added a task to be sure dns is installed and loaded, should be good now.
(don't know why you got this but at least the playbook is now sure the dns feature is started and enabled)

**Comment by ArnCo** [comment]
Hi there,

Sorry for reopening, but I just got the same issue while provisioning dc02:

```
fatal: [dc02]: FAILED! => {"changed": false, "msg": "The DnsServer module failed to load properly: The specified module 'DnsServer' was not 
loaded because no valid module file was found in any module directory."}                                                                    
```

Installing the DNS role manually for dc02 fixes the issue, so I suspect that adding the same task for the child_domain playbook would be a good idea.

Cheers,

ArnC
