### ISSUE TITLE
vm_disk_format error

### ISSUE THREAD

**Issue by mubix** [Orange-Cyberdefense/GOAD#148]
```
/GOAD/packer/proxmox# packer validate -var-file=windows_server2019_proxmox_cloudinit.pkvars.hcl .
Warning: Undefined variable

The variable "vm_disk_format" was set but was not declared as an input variable.
To declare variable "vm_disk_format" place this block in one of your .pkr.hcl
files, such as variables.pkr.hcl

variable "vm_disk_format" {
  type    = string
  default = null
}


Error: Unsupported attribute

  on packer.json.pkr.hcl line 35:
  (source code not available)

This object does not have an attribute named "vm_disk_format".

```
Version:
```
# packer version
Packer v1.9.4
```

Line 35:
```
    format            = "${var.vm_disk_format}"
```

**Comment by grumo35** [comment]
If you use ZFS on proxmox go for qcow2,

if not this should work :

grep "disk_format" *
packer/proxmox/config.auto.pkrvars.hcl:vm_disk_format             = "raw"
packer/proxmox/windows_server2019_proxmox_cloudinit.pkvars.hcl:vm_disk_format        = "raw"
packer/proxmox/variables.pkr.hcl:variable "vm_disk_format" {}
packer/proxmox/windows_server2016_proxmox_cloudinit.pkvars.hcl:vm_disk_format = "raw"
packer/proxmox/windows_10_22h2_proxmox_cloudinit.pkvars.hcl:vm_disk_format        = "raw"
packer/proxmox/packer.json.pkr.hcl:    format            = "${var.vm_disk_format}"

**Comment by mubix** [comment]
I'm working to follow the directions here, but they are a bit unclear.

1. I used `./scripts/setup_proxmox.sh` on my provisioner VM - one word of warning there is that it can really mess up your terminal since it uses `tee` to output binary to the screen on this line: https://github.com/Orange-Cyberdefense/GOAD/blob/4cdbab40f6af8044e3ace5e390ac7a6e8dc45043/scripts/setup_proxmox.sh#L17
2. I used `./goad.sh -t check -l GOAD -p proxmox` and everything checks out ok.
3. I then went to the Part 2 of @Mayfly277 's posts and:
  a. Downloaded the two ISOs to my proxmox `local` storage
  b. Downloaded the CloudBaseInitSetup file to my povisioner's sysprep directory
  c. Created a dedicated user on my proxmox server and gave it the right permissions
  d. Copied the template and edited the `config.auto.pkrvars.hcl` file with the correct information for my proxmox server
  e. Prepared the ISO files via `./build_proxmox_iso.sh`
  f. Copied over the `scripts_withcloudinit.iso` to my proxmox server
  g. Downloaded the `virtio-win.iso` to my proxmox server
  h. Ran `packer init .`
  g. Then I ran `packer validate -var-file=windows_server2019_proxmox_cloudinit.pkvars.hcl .` and ran into the error that was stated above:

```
Warning: Undefined variable

The variable "vm_disk_format" was set but was not declared as an input variable.
To declare variable "vm_disk_format" place this block in one of your .pkr.hcl
files, such as variables.pkr.hcl

variable "vm_disk_format" {
  type    = string
  default = null
}


Error: Unsupported attribute

  on packer.json.pkr.hcl line 35:
  (source code not available)

This object does not have an attribute named "vm_disk_format".
```
Was I supposed to populate the variables.pkr.hcl at some point? This is what mine looks like currently:
```
variable "proxmox_url" {}
variable "proxmox_username" {}
variable "proxmox_password" {}
variable "proxmox_skip_tls_verify" {}
variable "proxmox_node" {}
variable "proxmox_pool" {}
variable "proxmox_storage" {}
variable "winrm_username" {}
variable "winrm_password" {}
variable "vm_name" {}
variable "template_description" {}
variable "iso_file" {}
variable "autounattend_iso" {}
variable "autounattend_checksum" {}
variable "vm_cpu_cores" {}
variable "vm_memory" {}
variable "vm_disk_size" {}
variable "vm_sockets" {}
variable "os" {}
```

**Comment by Mayfly277** [comment]
fixed, sorry missed to commit the variable declaration ;) 
https://github.com/Orange-Cyberdefense/GOAD/commit/b006eecaf60374355f9504a06435cc40a0d977c9
