### ISSUE TITLE
NHA: The box you're attempting to add doesn't support the provider you requested

### ISSUE THREAD

**Issue by jianni20** [Orange-Cyberdefense/GOAD#149]
Trying to run `vagrant up` in NHA and I can't seem to figure out how to fix this. I've tried VirtualBox and VMware Workstation (Windows 11) and the result is the same. I've built GOAD on the same machine without any issues.
```
PS:2 >vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Box 'mayfly/windows_server2019' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'mayfly/windows_server2019'
    default: URL: https://vagrantcloud.com/api/v2/vagrant/mayfly/windows_server2019
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: mayfly/windows_server2019
Address: https://vagrantcloud.com/api/v2/vagrant/mayfly/windows_server2019
Requested provider: vmware_desktop vmware_fusion vmware_workstation (x64)
```

**Comment by Mayfly277** [comment]
I don't get why you got this issue, the provider vmware_desktop is well uploaded on vagrant cloud.
i don't know how to help you on this. This is the first time i see this issue.
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/23179648/bf43118c-fa31-443c-8794-fd2ca557445a)

**Comment by jianni20** [comment]
Yeah...I didn't see anything wrong either. Just posted in case someone else ran into the same issue. I'll keep troubleshooting and post back if I get it working.

Many thanks for this project. Really is great work you've done.
