### ISSUE TITLE
Problems in the ansible-playbook stage

### ISSUE THREAD

**Issue by laolong123** [Orange-Cyberdefense/GOAD#155]
Always appearing “no hosts matched”
<img width="1118" alt="IMG_9380" src="https://github.com/Orange-Cyberdefense/GOAD/assets/38502802/fecd3f9b-4e52-43f6-b29d-8f4c406eae0d">

**Comment by laolong123** [comment]
where is the file hosts？

**Comment by Mayfly277** [comment]
you missed the inventory files. (see here : https://github.com/Orange-Cyberdefense/GOAD/blob/main/docs/install_with_virtualbox.md#launch-provisioning-with-docker)

```bash
sudo docker run -ti --rm --network host -h goadansible -v $(pwd):/goad -w /goad/ansible goadansible ansible-playbook -i ../ad/GOAD/data/inventory -i ../ad/GOAD/providers/virtualbox/inventory main.yml
```
