### ISSUE TITLE
fatal: [dc02]: FAILED! => {"changed": true, "cmd": "dnscmd

### ISSUE THREAD

**Issue by daviosardinha** [Orange-Cyberdefense/GOAD#157]
Hi there, 
I'm running  the script `./goad.sh -t install -l GOAD -p vmware -m docker` and I get the following error. 
I've check this on issues and I haven't found anything related.

regards

TASK [child_domain : enable the Ethernet1 interface (local) for DNS client requests] ****************************************************************************************************************************************************************************************************************************************
fatal: [dc02]: FAILED! => {"changed": true, "cmd": "dnscmd . /resetlistenaddresses 192.168.56.11", "delta": "0:00:00.296992", "end": "2023-11-27 14:48:43.487922", "msg": "non-zero return code", "rc": 1, "start": "2023-11-27 14:48:43.190930", "stderr": "dnscmd : The term 'dnscmd' is not recognized as the name of a cmdlet, function, script file, or operable program. \r\nCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt line:1 char:65\r\n+ ... ::InputEncoding = New-Object Text.UTF8Encoding $false; dnscmd . /rese ...\r\n+                                                            ~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (dnscmd:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException", "stderr_lines": ["dnscmd : The term 'dnscmd' is not recognized as the name of a cmdlet, function, script file, or operable program. ", "Check the spelling of the name, or if a path was included, verify that the path is correct and try again.", "At line:1 char:65", "+ ... ::InputEncoding = New-Object Text.UTF8Encoding $false; dnscmd . /rese ...", "+                                                            ~~~~~~", "    + CategoryInfo          : ObjectNotFound: (dnscmd:String) [], CommandNotFoundException", "    + FullyQualifiedErrorId : CommandNotFoundException"], "stdout": "", "stdout_lines": []}
``

**Comment by daviosardinha** [comment]
![2023-11-27_14-56](https://github.com/Orange-Cyberdefense/GOAD/assets/30393912/0327f0dc-6254-4862-a431-e408e68d767b)

**Comment by juicemon-code** [comment]
@daviosardinha I get the same error. Did you fix this? 😥

**Comment by tititototutu** [comment]
Hello,

To fix the "dnscmd.exe not found"  issue:
- Log into the GAOD-DC2 VM with vagrant/vagrant credential
- launch a powershell terminal, then install Windows DNS  tools with:
`Install-WindowsFeature -Name DNS -IncludeManagementTools `
- Relaunch the configuration tool
`./goad.sh -t install -l GOAD -p virtualbox  -m docker `

Enjoy

**Comment by daviosardinha** [comment]
Thank you. that fixed my issue.

**Comment by hastalamuerte** [comment]
facing that issue right now. all ok after setup -> 

> Hello,
> 
> To fix the "dnscmd.exe not found" issue:
> 
>     * Log into the GAOD-DC2 VM with vagrant/vagrant credential
> 
>     * launch a powershell terminal, then install Windows DNS  tools with:
>       `Install-WindowsFeature -Name DNS -IncludeManagementTools `
> 
>     * Relaunch the configuration tool
>       `./goad.sh -t install -l GOAD -p virtualbox  -m docker `
> 
> 
> Enjoy
