### ISSUE TITLE
setup hangs at "WinRM transport: negotiate"

### ISSUE THREAD

**Issue by silbermano** [Orange-Cyberdefense/GOAD#160]
Hi,

I am trying to setup the environment on a Ubuntu 22.04, which runs on a VM at the cloud provider Strato.

For some reason the setup hangs at "WinRM transport: negotiate" and I have not managed to go past this. 
After a while I get the timeout error message

Could you give me a hint?

Below is the screenshot where I get stuck:

###################################################################
 ./goad.sh -t check -l GOAD -p virtualbox -m docker
./goad.sh -t install -l GOAD -p virtualbox  -m docker
[✓] Task: check
[✓] Lab: GOAD
[✓] Provider: virtualbox
[✓] Method: docker
[✓] folder ad/GOAD/providers/virtualbox found
[✓] Launch check : ./scripts/check.sh virtualbox docker
[+] Enumerating virtulabox
  [✓] virtualbox is installed
  [✓] Vagrant was found in your PATH
  [✓] Your version of Vagrant (2.4.0) is supported
  [✓] The vagrant-reload plugin is currently installed
  [✓] You have more than 120GB of free space on your primary partition
  [✓] You have more than 24GB of ram
  [✓] docker is installed
[✓] Check is ok, you can start the installation
[✓] Task: install
[✓] Lab: GOAD
[✓] Provider: virtualbox
[✓] Method: docker
[✓] folder ad/GOAD/providers/virtualbox found
[✓] Launch installation for: GOAD / virtualbox / docker
[✓] launch vagrant
Bringing machine 'GOAD-DC01' up with 'virtualbox' provider...
Bringing machine 'GOAD-DC02' up with 'virtualbox' provider...
Bringing machine 'GOAD-DC03' up with 'virtualbox' provider...
Bringing machine 'GOAD-SRV02' up with 'virtualbox' provider...
Bringing machine 'GOAD-SRV03' up with 'virtualbox' provider...
==> GOAD-DC01: Importing base box 'StefanScherer/windows_2019'...
==> GOAD-DC01: Matching MAC address for NAT networking...
==> GOAD-DC01: Checking if box 'StefanScherer/windows_2019' version '2021.05.15' is up to date...
==> GOAD-DC01: Setting the name of the VM: GOAD-DC01
==> GOAD-DC01: Clearing any previously set network interfaces...
==> GOAD-DC01: Preparing network interfaces based on configuration...
    GOAD-DC01: Adapter 1: nat
    GOAD-DC01: Adapter 2: hostonly
==> GOAD-DC01: Forwarding ports...
    GOAD-DC01: 5985 (guest) => 55985 (host) (adapter 1)
    GOAD-DC01: 5986 (guest) => 55986 (host) (adapter 1)
    GOAD-DC01: 22 (guest) => 2222 (host) (adapter 1)
==> GOAD-DC01: Running 'pre-boot' VM customizations...
==> GOAD-DC01: Booting VM...
==> GOAD-DC01: Waiting for machine to boot. This may take a few minutes...
    GOAD-DC01: WinRM address: 127.0.0.1:55985
    GOAD-DC01: WinRM username: vagrant
    GOAD-DC01: WinRM execution_time_limit: PT2H
    GOAD-DC01: WinRM transport: negotiate
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

###################################################################

Setting "config.vm.boot_timeout" does not help

Thanks

**Comment by Mayfly277** [comment]
https://github.com/Orange-Cyberdefense/GOAD/blob/main/docs/troubleshoot.md#vagrant-up---winrm---digest-initialization-failed--initialization-error
try one of these solution.
regards
