### ISSUE TITLE
Virtual Machines created with vagrant do not appear in virtualbox

### ISSUE THREAD

**Issue by k4n4n** [Orange-Cyberdefense/GOAD#161]
I have installed GOAD in Ubuntu, according to all the instructions to do so, however during the process of creating the virtual machines with vagrant they do not appear in virtualbox:

![Captura desde 2023-12-03 11-40-39](https://github.com/Orange-Cyberdefense/GOAD/assets/43685859/94cacbde-a4e1-4a6b-9490-628b17773d70)

However, when listing the virtual machines with vagrant status, they do appear

![Captura desde 2023-12-03 11-41-22](https://github.com/Orange-Cyberdefense/GOAD/assets/43685859/9cd1758d-4bbf-4a3e-9e14-6b090c44dd63)

I don't know what I can do to solve this,

Thanks, 

regards

**Comment by Mayfly277** [comment]
You have launch the install with sudo so your vm are available for root and not your user.
run sudo virtualbox and you will see your vm.
vagrant should be run as simple user, i do not recommend running virtualbox as root.
