### ISSUE TITLE
Stderr: Warning: program compiled against libxml 210 using older 209

### ISSUE THREAD

**Issue by pwnedDesal** [Orange-Cyberdefense/GOAD#164]
HI, try to run the `GOAD-Light` (vmware) after I run the vagrant up i got this error. The error still persist after I  installed `libxml2-dev ` 
**Host OS**
```
No LSB modules are available.
Distributor ID: Ubuntu
Ubuntu 22.04.3 LTS
22.04
jammy

```

Here is the full error log
```
== > GOAD-DC01: Cloning VMware VM: 'StefanScherer/windows_2019'. This can take some time ...
An error occurred while executing `vmrun', a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "snapshot", "/home/{reducted}/. vagrant.d/boxes/StefanScherer -VAGRANTSLASH-windows_2019/2021. 05. 15/vmware_desktop/WindowsServer2019. vmx
{:notify=>[:stdout, :stderr]}]

Stdout: Error: The operation is not supported

Stderr: Warning: program compiled against libxml 210 using older 209
```

**Comment by h4mr3r** [comment]
This is the warning only 
`Stderr: Warning: program compiled against libxml 210 using older 209,`
problem is that, the vmrun uses as default:
`-T player` 
but not
`-T ws`

**Comment by pwnedDesal** [comment]
> vagrant plugin install --plugin-version=3.0.1 vagrant-vmware-desktop

Hi, @h4mr3r Thank you for your reply. Unfortunately, the provided solution does not work on my machine. The problem still persist
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/6646675/cf53badb-0709-4613-811d-ad925cf7d444)

**Comment by h4mr3r** [comment]
As i can see the mentioned solution was solved @pwnedDesal.
From your response we can see that `Operation was canceled`, It could be because of

- lack of resources (diskspace, cpu, ram etc.)
- lack of permissions.
- a lot more of the reasons,  i don't know what's going on on ur computer, how did set the things up

it is worth mention that GOAD is in /opt/ directory, it could be lack of permissions :)

**Comment by PinhaFrita** [comment]
I am running into the same issue as @pwnedDesal , running Ubuntu 22.04 LTS. Tried to apply the fix that @h4mr3r suggested but it still runs into the same libxml 209/210 error. I do have GOAD on my user directory, and not on /opt.
May it be a issue with vmrun? 
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126058479/aa2b8ac2-7579-4836-865f-1f5b44f6ecb1)

**Comment by Mayfly277** [comment]
fixed by adding     v.force_vmware_license = "workstation" in the vagrantfile.
