### ISSUE TITLE
error on 'synchronizes all domains' step of goad install script

### ISSUE THREAD

**Issue by NeuroSpork** [Orange-Cyberdefense/GOAD#166]
I've been hitting this issue for the past few days, I've tried with multiple hosts, but have hit a vagrant fatal error at the same point. this is the error message I've been getting:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/6097113/5733a38a-c65e-48e7-83e6-9551b94fa6e8)

Is there a workaround for this?

I'm not super familiar with windows RPC debugging/errors, so I'm not sure what the next step is to troubleshoot.

**Comment by Mayfly277** [comment]
should be fix now
