### ISSUE TITLE
Issue in launching vagrant

### ISSUE THREAD

**Issue by dncdkf** [Orange-Cyberdefense/GOAD#173]
I am getting this error, what should I do?
![vagrant](https://github.com/Orange-Cyberdefense/GOAD/assets/60182783/659cdbc4-d1b5-43ed-a831-468375c5f464)

**Comment by Mayfly277** [comment]
This seems to be an error when vagrant try to create the new network device on vmware.
Did there is a conflict with another device already setup on 192.168.56.0/24 ?
You could also try to open vmware virtual network manager setup a vmnet manually hostonly for 192.168.56.0 and subnetmast 255.255.255.0 and see if it change something.
