### ISSUE TITLE
Missing WS01 in virtualbox/Vagrantfile

### ISSUE THREAD

**Issue by Bigyls** [Orange-Cyberdefense/GOAD#176]
Hello, 

After git clone and following instalation, WS01 is always missing in ansible playbook with fllowing errors:

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/74175999/ccca42ad-a4fb-4a1a-9076-ee629083191b)

In fact, in `ad/GOAD/providers/virtualbox` folder, the `inventory` file contain following line : `ws01 ansible_host=192.168.56.30 dns_domain=dc01 dict_key=ws01` but `Vagrantfile` doesn't contain following line : `{ :name => "GOAD-WS01", :ip => "192.168.56.30", :box => "mayfly/windows10", :os => "windows"},`. 

So, WS01 is never downloaded with vagrant up and ansible playblook can't find it.

https://github.com/Orange-Cyberdefense/GOAD/commit/cb18a7e4a66668cd57b31dbec4bb7da93b989866

**Comment by Bigyls** [comment]
https://github.com/Orange-Cyberdefense/GOAD/commit/cb18a7e4a66668cd57b31dbec4bb7da93b989866

**Comment by Mayfly277** [comment]
my bad, fixed ;)
