### ISSUE TITLE
PROXMOX - Unable to clone from template

### ISSUE THREAD

**Issue by GabrielKrueger** [Orange-Cyberdefense/GOAD#179]
Hey,

I followed the tutorial posted on your blog. During [Part 3, using Terraform](https://mayfly277.github.io/posts/GOAD-on-proxmox-part3-terraform/) the VMs get partly cloned, but terraform freezes with an error.

After using `TF_LOG=debug terraform apply "goad.plan"` (or just `TF_LOG=debug terraform apply`), usually 2-3 machines got created, but the configuration stops, exiting with following error (on all cloned VMs):

```
 [ERROR] vertex "proxmox_vm_qemu.srv03" error: error updating VM: 400 Parameter verification failed., error status: {"data":null,"errors":{"pool":"property is not defined in schema and the schema does not allow additional properties"}} 
(...)
```

First of all, I had to create the pool manually through the GUI anyway, because otherwise the installation doesn't even start.
( `[ERROR] vertex "proxmox_vm_qemu.srv03" error: 403 Permission check failed (pool 'GOAD' does not exist)` )

After the error occurred I tried removing the `pool` key from `goad.tf`. This leads to 3 machines being cloned, started but being in a deathloop, since the hard disks are not properly assigned.

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/156792187/668c5810-8de3-48f1-9808-6c063f1ac9f5)
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/156792187/40aa8fda-e16e-4b00-b3a4-19a522b5ab7a)
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/156792187/38730a07-2ec2-4118-870f-b6855bada6a3)

Any suggestions on how to fix this? I assume there must be an option to add pool to "the schema"?

EDIT: As referenced in #171 it does not work for me. However, [this](https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1878134269) worked.

**Comment by leek4leaks** [comment]
@GabrielKrueger when using the solution [https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1878134269](url), do you still remove the pool key from the main.tf file?

**Comment by Mayfly277** [comment]
#200 should solve the issue
