### ISSUE TITLE
How is this intended to be started after deployment? 

### ISSUE THREAD

**Issue by Eric4Smith** [Orange-Cyberdefense/GOAD#18]
Is this meant to be started from a certain user on a certain box? Or do you domain join your own box to start? Or just start on the same subnet and attack from the outside of AD?

**Comment by Mayfly277** [comment]
Remember this is not a challenge but a lab. You could start where you want with the user you want.
If you want to do more a pentest approach you should listen to @V0lk3n advice ;)
And if you are totally loss you could read the AD mindmap : https://orange-cyberdefense.github.io/ocd-mindmaps/ or my blog posts : https://mayfly277.github.io/posts/GOADv2-pwning_part1/ 

have fun :)
