### ISSUE TITLE
Error while ansible provisioning

### ISSUE THREAD

**Issue by strishin** [Orange-Cyberdefense/GOAD#182]
An unreachable error occurs at the very beginning of ansible provisioning.  All machines are running and available on the network.  Has anyone encountered something similar, maybe you know a solution?
```
fatal: [dc01]: UNREACHABLE! => {"changed": false, "msg": "basic: Bad HTTP response returned from server. Code 502", "unreachable": true}
fatal: [dc02]: UNREACHABLE! => {"changed": false, "msg": "basic: Bad HTTP response returned from server. Code 502", "unreachable": true}
fatal: [srv02]: UNREACHABLE! => {"changed": false, "msg": "basic: Bad HTTP response returned from server. Code 502", "unreachable": true}
fatal: [srv03]: UNREACHABLE! => {"changed": false, "msg": "basic: Bad HTTP response returned from server. Code 502", "unreachable": true}
fatal: [dc03]: UNREACHABLE! => {"changed": false, "msg": "basic: Bad HTTP response returned from server. Code 502", "unreachable": true}
```
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/36985765/ccdeff5f-91ef-4b2f-8967-2a2edfa794e6)

**Comment by Lumistika** [comment]
Hi, 
check if you VM ip are OK.
If it's good, try to uncomment : 
nano ad/GOAD/providers/virtualbox/inventory 
ansible_winrm_transport=basic
ansible_port=5985

**Comment by Mayfly277** [comment]
closed as no answer
