### ISSUE TITLE
Domain trust doesn't seem to be in place

### ISSUE THREAD

**Issue by NnB0121** [Orange-Cyberdefense/GOAD#185]
Hello everyone,

Following mayfly's guide about enumerating with a valid user "https://mayfly277.github.io/posts/GOADv2-pwning-part3/",

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/159722977/ee23c14e-256b-4f36-9b6a-09d917f1f791)

Domain trusts dont seem to be in place

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/159722977/d75136dc-b155-4227-a6ba-65e434ddffb3)

Maybe something went wrong during installation? I've ran ansible command more than once and it completed without any errors.

Any help would be appreciated.

Regards.

**Comment by r0bag** [comment]
I encountered errors during the installation:
Add a domain user/group from another Domain in the multi-domain forest to a domain group : winterfell.north.sevenkingdoms.local] ***
failed: [dc03] (item={'key': 'DragonsFriends', 'value': ['sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']}) => {"added": [], "ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "DragonsFriends", "value": ["sevenkingdoms.local\\tyron.lannister", "essos.local\\daenerys.targaryen"]}, "msg": "Could not find domain user, group, service account or computer named tyron.lannister", "removed": []}

**Comment by Mayfly277** [comment]
try to relaunch ansible install. is the problem is not fix, go as domain admin to each dc and delete the trusts link. Once that done relaunch the install.
