### ISSUE TITLE
Providing with terraform on proxmox: 400 Parameter verification failed

### ISSUE THREAD

**Issue by LL1201** [Orange-Cyberdefense/GOAD#188]
Hello,

I'm attempting to create a lab with Proxmox, and when I use Terraform to create the machines, I encounter the following error:

"Error: error updating VM: 400 Parameter verification failed., error status: {"data":null,"errors":{"pool":"property is not defined in schema and the schema does not allow additional properties"}}"
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/58180479/8e3b58dd-18b9-4809-bf71-7fe445985025)

Solution #171 doesn't work for me. Then, I tried #179, but once again it didn't work.

If I create the machines without the 'pool' property, they are successfully created. However, upon starting them, they enter in a boot loop.

**Comment by reaperleo** [comment]
Hi,

https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1878134269 This work for me

**Comment by leek4leaks** [comment]
Haven't been able to get this working, are there other possible  solutions for this issue?
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/43292600/37ff7be9-e34a-405b-ab0f-bef3d8b934da)

**Comment by Mayfly277** [comment]
#200 should solve the issue
