### ISSUE TITLE
Error while adding domain/user group from another domain (ad-relations.yml)

### ISSUE THREAD

**Issue by IscarioteSXIII** [Orange-Cyberdefense/GOAD#19]
Hi guys, i'm having some issue with ad-relations.yml

Previously, i had some error with MSSQL installation, but was able to troubleshoot it. But now i'm facing a new issue while installing ad-relations.yml. Here's the following errors. i cant add
 I don't understand, the servers are up and running but it seems i can add other users, even if i'm doing it manually with users and computers tools. i took some snapshot, i tried to launch the playbook countless times, but error still persist
Here's the following error:

win_reboot: attempting post-reboot test command
EXEC (via pipeline wrapper)
win_reboot: attempting post-reboot test command
EXEC (via pipeline wrapper)
win_reboot: system successfully rebooted
changed: [192.168.56.11] => {
    "changed": true,
    "elapsed": 181,
    "rebooted": true,
    "unreachable": false
}

TASK [groups_domains : Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}}] *******************************************************************************
task path: /home/sparda/Documents/GIT/GOAD/ansible/roles/groups_domains/tasks/main.yml:5
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
<192.168.56.11> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.56.11
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
<192.168.56.12> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.56.12
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4
}
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4
}
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).Result was: {
    "attempts": 2,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4
}
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).Result was: {
    "attempts": 2,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4
}
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4
}
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
The full traceback is:
Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.
At line:64 char:21
+ ... up_member = Get-ADObject -Filter "SamAccountName -eq '$member' -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-ADObject], ADServerDownException
    + FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.GetADObject

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 64

Microsoft.ActiveDirectory.Management.ADServerDownException: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running. ---> System.ServiceModel.EndpointNotFoundException: No DNS entries exist for host north.sevenkingdoms.local.

Server stack trace: 
   at System.ServiceModel.Channels.DnsCache.Resolve(Uri uri)
   at System.ServiceModel.Channels.SocketConnectionInitiator.GetIPAddresses(Uri uri)
   at System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.ActiveDirectory.WebServices.Proxy.Resource.Get(Message request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   --- End of inner exception stack trace ---
   at Microsoft.ActiveDirectory.Management.AdwsConnection.InitializeForAutoReconnect[TChannel](Boolean& isAutoReconnecting, TChannel& channel, ChannelFactory`1& chFactory, String endpointName, CommunicationException& commException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetConnectedStore()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetCmdletSessionInfo()
   at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'DragonsFriends', 'value': ['north.sevenkingdoms.local\\jon.snow', 'sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']}) => {
    "ansible_loop_var": "item",
    "attempts": 3,
    "changed": false,
    "item": {
        "key": "DragonsFriends",
        "value": [
            "north.sevenkingdoms.local\\jon.snow",
            "sevenkingdoms.local\\tyron.lannister",
            "essos.local\\daenerys.targaryen"
        ]
    },
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running."
}
Using module file /home/sparda/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "msg": "Unhandled exception while executing module: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.",
    "retries": 4

**Comment by ulfklose** [comment]
I think, I'm having a similar error:

```
TASK [groups_domains : Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}}] ******************************************************
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'DragonsFriends', 'value': ['north.sevenkingdoms.local\\jon.snow', 'sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "DragonsFriends", "value": ["north.sevenkingdoms.local\\jon.snow", "sevenkingdoms.local\\tyron.lannister", "essos.local\\daenerys.targaryen"]}, "msg": "Unhandled exception while executing module: Either the target name is incorrect or the server has rejected the client credentials."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.11] (item={'key': 'AcrossTheSea', 'value': ['essos.local\\daenerys.targaryen']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "AcrossTheSea", "value": ["essos.local\\daenerys.targaryen"]}, "msg": "Unhandled exception while executing module: Authentication failed on the remote side (the stream might still be available for additional authentication attempts)."}
changed: [192.168.56.12] => (item={'key': 'Spys', 'value': ['sevenkingdoms.local\\Small Council']})
```

**Comment by IscarioteSXIII** [comment]
I was able to troubleshoot it and ad-relations is OK now ;) 
i purged ansible, installed venv like requested and ansible-core 2.13, everything is ok now ;)

(ansible) [sparda@Pandemonium ansible]$ ansible-playbook ad-relations.yml 

PLAY [Read data files] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.10]
ok: [192.168.56.22]
ok: [192.168.56.23]
ok: [192.168.56.11]

TASK [save the Json data to a Variable as a Fact] ******************************************************************************************************************************************************************
ok: [192.168.56.10]
ok: [192.168.56.11]
ok: [192.168.56.22]
ok: [192.168.56.12]
ok: [192.168.56.23]

PLAY [Adjust rights configuration] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.23]
ok: [192.168.56.10]
ok: [192.168.56.11]
ok: [192.168.56.22]

TASK [settings/adjust_rights : Add domain users to local groups] ***************************************************************************************************************************************************
changed: [192.168.56.22] => (item={'key': 'Administrators', 'value': ['north\\jeor.mormont']})
changed: [192.168.56.12] => (item={'key': 'Administrators', 'value': ['essos\\daenerys.targaryen']})
changed: [192.168.56.23] => (item={'key': 'Administrators', 'value': ['essos\\khal.drogo']})
changed: [192.168.56.10] => (item={'key': 'Administrators', 'value': ['sevenkingdoms\\robert.baratheon', 'sevenkingdoms\\cersei.lannister']})
changed: [192.168.56.11] => (item={'key': 'Administrators', 'value': ['north\\eddard.stark', 'north\\catelyn.stark', 'north\\robb.stark']})
changed: [192.168.56.12] => (item={'key': 'Remote Desktop Users', 'value': ['essos\\Targaryen']})
changed: [192.168.56.10] => (item={'key': 'Remote Desktop Users', 'value': ['sevenkingdoms\\Small Council']})
changed: [192.168.56.22] => (item={'key': 'Remote Desktop Users', 'value': ['north\\Night Watch', 'north\\Mormont', 'north\\Stark']})
changed: [192.168.56.11] => (item={'key': 'Remote Desktop Users', 'value': ['north\\Stark']})

PLAY [cross domain groups] *****************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.10]
ok: [192.168.56.11]

TASK [groups_domains : Reboot and wait for the AD system to restart] ***********************************************************************************************************************************************
changed: [192.168.56.10]
changed: [192.168.56.12]
changed: [192.168.56.11]

TASK [groups_domains : Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}}] *******************************************************************************
changed: [192.168.56.12] => (item={'key': 'DragonsFriends', 'value': ['north.sevenkingdoms.local\\jon.snow', 'sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']})
changed: [192.168.56.11] => (item={'key': 'AcrossTheSea', 'value': ['essos.local\\daenerys.targaryen']})
changed: [192.168.56.12] => (item={'key': 'Spys', 'value': ['sevenkingdoms.local\\Small Council']})

PLAY RECAP *********************************************************************************************************************************************************************************************************
192.168.56.10              : ok=6    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
192.168.56.11              : ok=7    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.56.12              : ok=7    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.56.22              : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.56.23              : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by ulfklose** [comment]
I just re-ran the whole Playbook which resolved almost all of my errors.

**Comment by IscarioteSXIII** [comment]
Honestly, i re-ran it countless times since Friday, and issue was still the same...until this morning. Re-installing Ansible and venv.

**Comment by Mayfly277** [comment]
Nice if all issues are gone.
have fun with the lab ;)

**Comment by Jugulaire** [comment]
@IscarioteSXIII could you please give us more info ? 
I have the same issue ans cannot get it to work..

**Comment by IscarioteSXIII** [comment]
Honestly, like i said, it was an issue with Ansible version and probably my python venv. But I'm pretty sure downgrading my Ansible to the same version recommended in the readme fixed the issue
