### ISSUE TITLE
Ansible ADServiceAccount error

### ISSUE THREAD

**Issue by reaperleo** [Orange-Cyberdefense/GOAD#192]
Hello,

I'm attempting to create a lab with Proxmox and Ansible gives me this error. 

: "internal error: failed to become user 'essos.local\\Administrator': Exception calling \"CreateProcessAsUser\" with \"9\" argument(s): \"The trust relationship between this workstation and the primary domain failed.\r\n\""}

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/10296800/831a4b2b-0ff4-4f7e-a9ee-447da13828bb)

can please someone help

**Comment by 137137137137** [comment]
How did you resolve this?
