### ISSUE TITLE
[Question] Bridge networking

### ISSUE THREAD

**Issue by TechnoJaguar** [Orange-Cyberdefense/GOAD#196]
How can I configure this so that the IP's of the machines are accessible by the rest of my network?
How do I change it from hostonlyif to a bridged, is this in a config somewhere?

I've tried changing IPs in the inventory and Vagrantfile but not getting far

Thanks!

**Comment by Mayfly277** [comment]
please do not do that! goad is a super vulnerable lab you don't want to put it into your network.
add a linux vm inside the same network as goad and use it to bounce on goad network.

**Comment by TechnoJaguar** [comment]
I want to test a pentesting app my company develops using it, so I can show what a, "vulnerable environment" looks like. This is in a purpose built DMZ.

**Comment by Mayfly277** [comment]
ok do it at your own risk ^^
you should not touch the host_only adapter and change the "nat" adapter manually to bridged to get the vm into the network.

**Comment by TechnoJaguar** [comment]
> ok do it at your own risk ^^ you should not touch the host_only adapter and change the "nat" adapter manually to bridged to get the vm into the network.

What file/line would this be in?

I want to put it in 10.10.50.0/24 subnet and just get DHCP for all machines so I don't have to worry if I decide to deploy a couple different environments (different groups within the business show different security products)

Using docker deployment method

**Comment by Mayfly277** [comment]
no lines, you have to change it manually on the provider you use.

**Comment by TechnoJaguar** [comment]
Not sure if I'm clear on how I'd manually change that, I've not used
vagrant before.

**Comment by cyberelic** [comment]
yeah im also trying to do this. ive tried going through the vagrant files but no luck yet.
