### ISSUE TITLE
Running Initial Install and Vagrantfiles missing

### ISSUE THREAD

**Issue by djdavid1982** [Orange-Cyberdefense/GOAD#197]
I am new to this and learning how to use Ansible. When I do the vagrant up, i get the error that there is no Vagrantfile. When I look at the directory, that is correct. None exist. Are we suppose to make one or is this suppose to be provided by the repo? Every video that ive watched doesnt show if this file exists or not.

**Comment by bannsec** [comment]
Follow their [quick install](https://github.com/Orange-Cyberdefense/GOAD?tab=readme-ov-file#tldr-quick-install) instructions on the front page.

**Comment by Mayfly277** [comment]
you didn't read the doc, i close the issue.
