### ISSUE TITLE
incorrect password for sansa.stark in lab config

### ISSUE THREAD

**Issue by colebaty** [Orange-Cyberdefense/GOAD#201]
I believe the password for `sansa.stark` is incorrect in the file `/ad/GOAD/data/config.json` [link to file](https://github.com/Orange-Cyberdefense/GOAD/blob/e3ecaceb264265fd163f14f98da3e0585e9cedbb/ad/GOAD/data/config.json)

What's written: `345etrdfg`
What I suspect it should be: `345ertdfg`

Reason: In the [vulnerability documentation](https://github.com/Orange-Cyberdefense/GOAD/blob/main/ad/GOAD/README.md#usersgroups-and-associated-vulnerabilitesscenarios), it says that `sansa.stark`'s password is a keywalking password. What's contained in the config file appears to be a typo.

This is easily fixed locally, and I'll make the change the next time I build the lab.  Just thought you'd want to know in case you wanted to include it in the next release.

I LOVE THIS PROJECT, btw.  Thank you so much for putting this together.

**Comment by Mayfly277** [comment]
you right, thx !
fixed :)
