### ISSUE TITLE
Lab all set up. Connected to the VPN ...but i cant reach the hosts

### ISSUE THREAD

**Issue by mqzinoo** [Orange-Cyberdefense/GOAD#212]
I created the lab and can VPN in successfully however when I ran an nmap scan on the network 192.168.10.0/24 I do not get any results. I have a feeling the issue is from the firewall rules but I cant figure it out. I am able to ping the attacker host from any of the target servers but not vice versa . can any one help me figure this out?

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/166086347/5b5f2339-c5f7-4c80-8b57-217fe855712c)

Firewall rules

WAN
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/166086347/cd1770f2-d0ef-4156-a66d-fa825de682f2)

LAN
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/166086347/cb28f5d3-72a5-47d0-bc91-019ec6404a93)

VLAN10
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/166086347/98709caf-43e2-468d-8835-d40a23d2ce7f)

VPN
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/166086347/e9231242-6bce-4b20-bd8b-3261389f1926)

**Comment by M-Davies** [comment]
Think I've got a similar issue to you #233
