### ISSUE TITLE
GOAD Exchange lab

### ISSUE THREAD

**Issue by lap1nou** [Orange-Cyberdefense/GOAD#219]
Greetings,

First of all, thank you for this project.

I was wondering if someone was working on an Exchange lab for GOAD.

I'm currently working on an Exchange install using Ansible but it need to be polished a bit. If you are interested I could begin a pull request but I just wanted to know if this was already in the pipe before continuing working on this.

Here is some of the things we could do maybe:

- [ ] W10 workstation with an Outlook client
- [ ] Proxylogon vulnerability
- [ ] PrivExchange
- [ ] Maybe some AD misconfig (Exchange admin overpowered)

(Sorry if this isn't the right place to talk about that, but I didn't knew where to post that)

Regards.

**Comment by viris** [comment]
was looking a bit into these:
- https://github.com/jborean93/exchange-test-environment seems to have a semi usable role to install Exchange, though it requires ISO to be mounted
- https://github.com/clong/DetectionLab/blob/master/Vagrant/scripts/ DetectionLab did install Exchange via PowerShell script
- you can get specific Exchange ISOs from MS download page https://learn.microsoft.com/en-us/exchange/new-features/updates?view=exchserver-2019, but yeah different versions have different vulns
- PrivExchange requires Exchange 2019 RTM or lower

**Comment by aleemladha** [comment]
@viris @lap1nou  Hi, i am working on building a range like you mentioned :) 
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/26311391/408d41c6-b7fe-4754-909c-258b277d8796)

**Comment by aleemladha** [comment]
@viris @aleemladha @mubix 
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/26311391/225f37b4-668f-4fb0-b27f-ebd9531b90b4)

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/26311391/2c29210e-e9e5-4a39-807a-c29e69549e61)

**Comment by lap1nou** [comment]
Awesome @aleemladha !, I really hope this got merged once it's ready.
