### ISSUE TITLE
Host Unreachable on 5986

### ISSUE THREAD

**Issue by raghavmishra** [Orange-Cyberdefense/GOAD#22]
For one host I am getting unreachable,
```
<192.168.56.22> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.56.22
fatal: [192.168.56.22]: UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='192.168.56.22', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10bfd7820>, 'Connection to 192.168.56.22 timed out. (connect timeout=500)'))",
    "unreachable": true
}
```

**Comment by raghavmishra** [comment]
Debugged that problem, now into other problem,
```
fatal: [192.168.56.22]: UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='192.168.56.22', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10ad68ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "unreachable": true
}
```
Now I am getting connection refused. Following other VM firewall rules added fw rule for 5986 but no luck.

**Comment by raghavmishra** [comment]
Resolved this issue by provisioning SRV02 again. The certificate was not generated initially that's it was not accepting conn on 5986.

**Comment by IscarioteSXIII** [comment]
How were you able to troubleshoot your first issue please ? I'm trying to deploy the VMs on my ESXi, but host are unreachable, even if I can ping the server.

**Comment by raghavmishra** [comment]
Hi IscarioteSXIII,
If you see on the host the firewall is still enabled that's why the unreachable message. **You go and disable the firewall manually** or destroy that single VM and re-run the script for that VM again. I tried the option in bold and it worked.
After resolving this issue I was getting "Connection Refused", so I went to the box and tried enabling the winRM over HTTPS manually, which gave me the error "trusted cert can't be found". That's the reason "connection refused" as WinRM over HTTPS was not running. For this I simply destroy the VM because the cert should have been created automatically but this cert can be created manually too. Just choose the option of destroying the VM.
Remember, just destroy a single VM and create that VM using vagrant.

**Comment by aancw** [comment]
I've the same issue when running ansible, the problem was blocked by windows firewall. I even can't ping the host. Disable the windows firewall for public & private network, solve the problem.

![Screen Shot 2022-07-25 at 11 44 41](https://user-images.githubusercontent.com/6284204/180700301-57c07079-a609-4770-949d-b5db2615a10d.png)

After that, i got the same connection refused for all the server. Is there any solution than destroying the vm?

![Screen Shot 2022-07-25 at 11 45 43](https://user-images.githubusercontent.com/6284204/180700406-7336aa48-4e4c-46af-a32e-5220cff78a77.png)

**Comment by aancw** [comment]
Confirmed, it work. So, for anyone having problem in ansible time out or connection refuse using deployer except vagrant, please put that 2 script in your deployer and run the scripts.

![Screen Shot 2022-07-25 at 20 36 34](https://user-images.githubusercontent.com/6284204/180790333-b07774d9-ccb0-4af3-b472-b4d897e968e5.png)
