### ISSUE TITLE
Error connecting to SQL port 1433 on SRV03

### ISSUE THREAD

**Issue by thesinghsec** [Orange-Cyberdefense/GOAD#227]
- Every time I run the script it returns the below error.
- The port is correctly configured on SQL configuration.
- I'm using VMWare to set up the lab GOAD.
- Apart from this error lab successfully deployed, but can't able to find the solution to the below error.

Please help to resolve this issue.
Even I tried uninstalling fully mssql from SRV03, but again no luck.

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126919241/a449306f-a60d-41c5-8ed5-51e64a0d54ae)

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126919241/7545df14-b844-4e33-b543-f89c96fcbcb1)

The latest snapshot of the current error:
![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126919241/6ac4e0ed-9606-4e13-98c6-608d9be086ab)

- One difference I noticed between SEV02 and SRV03 is that "SQL Server (SQLEXPRESS)" keeps running in SRV02 but on SRV03 if eventually stops even after trying to manually set it on, it automatically turns off with no time.

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126919241/4c80e061-ef96-4f56-b9fa-f6586175f74f)

![image](https://github.com/Orange-Cyberdefense/GOAD/assets/126919241/0bb2014e-5f3d-44fe-bebb-4bb7f9c19af6)

**Comment by AungSoePaing** [comment]
same error

**Comment by jvinnedge** [comment]
I'm also seeing this issue with SRV03. I'm using virtualbox with vagrant.

**Comment by Mayfly277** [comment]
something was wrong during srv03 creation, imo uninstall mssql manually and relaunch the install.
