### ISSUE TITLE
Ansible Task "disable interface Ethernet before join domain" fails

### ISSUE THREAD

**Issue by CalvinXPLT** [Orange-Cyberdefense/GOAD#23]
Hello,

when running the ansible-playbook main.yml, the script runs into the following issue:

```
TASK [child_domain : disable interface Ethernet before join domain] *******************************************************
fatal: [172.18.100.11]: FAILED! => {"changed": true, "cmd": "netsh interface set interface \"Ethernet\" disable", "delta": "0:00:00.906198", "end": "2022-07-22 06:32:15.861635", "msg": "non-zero return code", "rc": 1, "start": "2022-07-22 06:32:14.955437", "stderr": "", "stderr_lines": [], "stdout": "No more data is available.\r\n\r\n\r\n", "stdout_lines": ["No more data is available.", "", ""]}
```

From my first look at the issue, this appears to be cause by the fact that the standard network interface in Server 2019 is called "Ethernet0" instead of "Ethernet".

The server itself is reachable though.
Any help would be appreciated.

**Comment by aancw** [comment]
Change the main.yml script from Ethernet to Ethernet0

**Comment by CalvinXPLT** [comment]
Thanks

**Comment by IscarioteSXIII** [comment]
i dont understand whats the point to disable the ethernet interface when you're joining domain. Can you explain why it has to be disable ? When troubleshooting my install on my ESXi, that step gave me trouble and i had to comment the "disable ethernet interface" lines

Now, ive been able to install the lab on my server (Vsphere 6.7 on an old DELL Poweredge T420 (20core, 40threads, 256 Go RAM) and its working great ;) (i had to provision and set vms manually, i'll play with vagrant and vsphere plugin after holidays)

Many thanks for your work...Now its time to pwn the lab

**Comment by aancw** [comment]
> i dont understand whats the point to disable the ethernet interface when you're joining domain. Can you explain why it has to be disable ? When troubleshooting my install on my ESXi, that step gave me trouble and i had to comment the "disable ethernet interface" lines
> 
> Now, ive been able to install the lab on my server (Vsphere 6.7 on an old DELL Poweredge T420 (20core, 40threads, 256 Go RAM) and its working great ;) (i had to provision and set vms manually, i'll play with vagrant and vsphere plugin after holidays)
> 
> Many thanks for your work...Now its time to pwn the lab

I'm using esxi and deleted the line. So my ethernet is not disabled. Because there's only the way ansible can connect to the host.

**Comment by Zxxxx** [comment]
main.yml script not found Ethernet 

commit 4774a5be96ace654d33367abb646f74e54cae8e7 (HEAD -> main, origin/main, origin/HEAD)
Author: Mayfly277 <mayfly277@gmail.com>
Date:   Mon Feb 20 10:40:43 2023 +0100


![image](https://user-images.githubusercontent.com/19280377/221137227-7053a39e-7c66-4e43-9a0a-08f3db5933e9.png)
