### ISSUE TITLE
 EOF Build 'proxmox-iso.windows' errored after 5 seconds 38 milliseconds: Post "https://proxmox-IP:8006/api2/json/nodes/proxmox-goad/storage/local/upload": EOF

### ISSUE THREAD

**Issue by TonyDAtigerr** [Orange-Cyberdefense/GOAD#234]
I really wanted to refrain from posting but I am kind of desperate to get this server standing up. Anytime I try to use packer to build I get the error shown in the screenshots below. I have gone through the setup multiple times but as you can see from the syslog its is not a authentication problem. I can ping both ways and even curl the proxmox API from my provisioning machine. If anyone could assist it would be greatly appreciated.

![syslog](https://github.com/Orange-Cyberdefense/GOAD/assets/96063334/64b1cde5-11fb-4ec2-8f74-0da041d11591)

![packer_error](https://github.com/Orange-Cyberdefense/GOAD/assets/96063334/aa65b3ee-f021-46b2-ac00-6af3a4f084fb)

![pve_log](https://github.com/Orange-Cyberdefense/GOAD/assets/96063334/bb70dc41-a164-4be2-a98a-880381e57416)

**Comment by Gromiton** [comment]
did you solve this, I am having the same issue

**Comment by TonyDAtigerr** [comment]
Never was able to figure it out, never visited back to it, too many errors and not enough context behind the write up.

**Comment by Mayfly277** [comment]
it is a packer issue, after an update should be ok i guess.
