### ISSUE TITLE
WSL Migration

### ISSUE THREAD

**Issue by superteece** [Orange-Cyberdefense/GOAD#25]
I'm working on getting GOAD to launch on the Windows host by using Vagrant within WSL. The process is working up to the winrm connection. Vagrant is trying to connect to 127.0.0.1 but I need to to use the Windows host address instead. Where do I change that? It's not jumping out at me in the Vagrantfile.

**Comment by V0lk3n** [comment]
It will be hard on WSL2, if i remember correctly WSL1 use the host ip address, so just une WSL1 as default version for the linux instance where variant run

**Comment by V0lk3n** [comment]
It will be hard on WSL2, if i remember correctly WSL1 use the host ip address, so just une WSL1 as default version for the linux instance where variant run

Edit : I've tested and confirm it

```
wsl --set-version <your distro> 1
```

This will allow the distro to share the same windows host ip address instead the 172.168.x.x address of WSL2

**Comment by Mayfly277** [comment]
thx for your answer @V0lk3n.
@superteece  is this ok ? can i close the issue ?

**Comment by superteece** [comment]
I'd prefer to not switch to WSL1 so I'm experimenting with some other ways to go about my issue. I've switch over to the base Vagrant project that GOAD uses so yeah go ahead and close this. 

I'll report back if I figure out a method.

Thanks for the awesome project though! Worked easily on one of my Linux machines, as advertised.

**Comment by V0lk3n** [comment]
> I'd prefer to not switch to WSL1 so I'm experimenting with some other ways to go about my issue. I've switch over to the base Vagrant project that GOAD uses so yeah go ahead and close this. 
> 
> I'll report back if I figure out a method.
> 
> Thanks for the awesome project though! Worked easily on one of my Linux machines, as advertised. 

No need to switch on WSL1, you can just add another WSL instance like ubuntu dedicated for GOAT and put this one as WSL1, and stay on WSL2 on your "main" instance ^^

**Comment by V0lk3n** [comment]
And your welcom @Mayfly277 :D
