### ISSUE TITLE
Not able to setup DC02 system, ansible script throwing error while setting password policy

### ISSUE THREAD

**Issue by 0xn1k5** [Orange-Cyberdefense/GOAD#26]
TASK [password_policy : set password policy] *****************************************************************************
fatal: [192.168.56.11]: FAILED! => {"changed": true, "debug": [], "error": [{"category_info": {"activity": "Set-ADDefaultDomainPasswordPolicy", "category": "ResourceUnavailable", "category_id": 21, "reason": "ADServerDownException", "target_name": "WORKGROUP", "target_type": "ADDefaultDomainPasswordPolicy"}, "error_details": null, "exception": {"help_link": null, "hresult": -2146233088, "inner_exception": {"help_link": null, "hresult": -2146233088, "inner_exception": null, "message": "Unable to find a default server with flags: 'Writable | ADWS | ReturnDnsName'.", "source": null, "type": "Microsoft.ActiveDirectory.Management.ADException"}, "message": "Unable to find a default server with Active Directory Web Services running.", "source": "Microsoft.ActiveDirectory.Management", "type": "Microsoft.ActiveDirectory.Management.ADServerDownException"}, "fully_qualified_error_id": "ActiveDirectoryServer:1355,Microsoft.ActiveDirectory.Management.Commands.SetADDefaultDomainPasswordPolicy", "output": "Set-ADDefaultDomainPasswordPolicy : Unable to find a default server with Active Directory Web Services running.\r\nAt line:19 char:1\r\n+ Set-ADDefaultDomainPasswordPolicy -Identity $Domain -AuthType Negotia ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ResourceUnavailable: (WORKGROUP:ADDefaultDomainPasswordPolicy) \r\n[Set-ADDefaultDomainPasswordPolicy], ADServerDownException\r\n    + FullyQualifiedErrorId : \r\nActiveDirectoryServer:1355,Microsoft.ActiveDirectory.Management.Commands.SetADDefaultDomainPasswordPolicy\r\n \r\n", "pipeline_iteration_info": [0, 1], "script_stack_trace": "at <ScriptBlock>, <No file>: line 19", "target_object": {"AddedProperties": [], "ComplexityEnabled": null, "LockoutDuration": null, "LockoutObservationWindow": null, "LockoutThreshold": null, "MaxPasswordAge": null, "MinPasswordAge": null, "MinPasswordLength": null, "ModifiedProperties": [], "PasswordHistoryCount": null, "PropertyCount": 0, "PropertyNames": [], "RemovedProperties": [], "ReversibleEncryptionEnabled": null}}], "host_err": "", "host_out": "", "information": [], "output": [], "result": {}, "verbose": [], "warning": []}

PLAY RECAP ***************************************************************************************************************
192.168.56.11              : ok=27   changed=6    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by iNoSec2** [comment]
Did you tried to make the password match the password policy?

**Comment by Mayfly277** [comment]
You got the error "ResourceUnavailable". May be the server 192.168.56.11 was to busy at the time of provisioning ? Could you retry the provisioning and see if it fail again ?

**Comment by CleverNamesTaken** [comment]
I got the same error.  It doesn't apper to be a problem with the provisioning -- I think it is because it isn't yet connected to the sevenkingdoms.local domain.

**Comment by CleverNamesTaken** [comment]
The problem was DNS.  

I'm trying to set up with WSL and Virtual Box, and I didn't know what to do with the network adapters.  Disabling the NAT network adapter and configuring the network adapter on the 192.168.56.0/24 network to use 192.168.56.10 as the DNS server resolved this for me.

**Comment by Mayfly277** [comment]
@0xn1k5 you could try to connect to dc02 (192.168.56.11), run a `gpupdate` as vagrant user and after that relaunch the playbooks.

**Comment by Mayfly277** [comment]
remove the nat network during domain installation and trust creation fix the problems. fixed in #52
