### ISSUE TITLE
Vmware requires a GUI

### ISSUE THREAD

**Issue by MelForze** [Orange-Cyberdefense/GOAD#263]
Hi, thanks for the GOAD and SCCM. I am trying to install SCCM, I encountered that why the OOB module for mysql was not installed in virtualbox and tried to install via vmware, but vmware requires a GUI when installing/starting virtual machines. Should I make it so that it does not require this and users can remotely e.g. deploy the lab without GUI?

**Comment by Mayfly277** [comment]
just comment the gui part in the vagrantfile : 
![Uploading image.png…]()
