### ISSUE TITLE
No match was found for the specified search criteria and module name 'ActiveDirectoryDSC'

### ISSUE THREAD

**Issue by hybla0** [Orange-Cyberdefense/GOAD#272]
Hi,
i am trying to deploy goad-light made standard vagrant provisioning, checked interface addresses to be correct,

launched provisioning with ansible:

./goad.sh -t install -l GOAD-light -p vmware -m local -a

and i get :

`fatal: [dc01]: FAILED! => {"changed": false, "msg": "Problems installing ActiveDirectoryDSC module: No match was found for the specified search criteria and module name 'ActiveDirectoryDSC'. Try Get-PSRepository to see all available registered module repositories.", "nuget_changed": false, "output": "", "repository_changed": false}`

**Comment by hybla0** [comment]
> Can you make sure the VM is properly connected to the Internet? I had the same issue, and it was because the gateway was reset.

it was that the adapter type was wrong and local dns server not configured by ansible so i had to input it manually

**Comment by p3452** [comment]
> Can you make sure the dc01 VM is properly connected to the Internet? I had the same issue, and it was because the gateway was reset.



> > Can you make sure the VM is properly connected to the Internet? I had the same issue, and it was because the gateway was reset.
> 
> it was that the adapter type was wrong and local dns server not configured by ansible so i had to input it manually

hi, can you give more details, for which network adapter are you talking about the ideas, and what dns did you register? I tried to set auto dns on the first adapter and from all dc there is access to the internet from cmd
