### ISSUE TITLE
VM not Booting 

### ISSUE THREAD

**Issue by Ibouro** [Orange-Cyberdefense/GOAD#274]
hello
when I run the command ./goad.sh -t install -l GOAD -p virtualbox -m docker
I get this error

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3cd73734-6cda-4fbc-9ad0-b00249d5bc1b", "--type", "headless"]

Stderr: Warning: program compiled against libxml 212 using older 209
VBoxManage: error: Out of memory condition when allocating memory with low physical backing. (VERR_NO_LOW_MEMORY)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

thanks

**Comment by th3g3ntl3m4n84** [comment]
Having this problem with the Virtual Box too.

**Comment by Mayfly277** [comment]
close as it is related to vbox+vagrant not goad. but thx for the workarround !
