### ISSUE TITLE
Instructional Video for Installation

### ISSUE THREAD

**Issue by mother2110** [Orange-Cyberdefense/GOAD#28]
Are they any instructional videos on how to build this? I have a laptop with 1TB SSH and 32 GB mem. It is running Ubuntu Desktop 22.04. Do I install Vbox and then another Ubuntu VM and then follow the instructions? How much ram and storage do I give the VM? Can I run vbox on Windows with a Ubuntu VM?

Thanks

**Comment by Yrroth** [comment]
You just install Vagrant, Install Additional Provider if using VMWare if not vbox works default.
Vagrant Up and it'll build takes 1-2hrs
Once built you can use a Kali VM to Scan the 192.168.56.0 Range which is listed in the vagrant file unless you changed which would be provided network. You'll need to research some active directory type testing tools like responder and others to get much and get into network.

**Comment by mother2110** [comment]
So I just install this on a bare metal desktop (Linux) with vbox and vagrant installed and just vagrant up? Thats it?

**Comment by Yrroth** [comment]
Essentially yea. vagrant uses providers like VirtualBox or VmWare or some others to build VirtualMachines behind the scenes. It references the vagrantfile which has all the steps and back and back technical stuff.

**Comment by mother2110** [comment]
Awesome. Thank you so much, I will attempt this first thing in the morning.

**Comment by mother2110** [comment]
Thank you
