### ISSUE TITLE
Typo in SRV02 hostname - Castleblack vs Castelblack

### ISSUE THREAD

**Issue by bdesforges** [Orange-Cyberdefense/GOAD#282]
Looks like there is a typo in the way SRV02 hostname has been spelt. 

It probably should be **castleblack** as opposed to castelblack. 

Probably not that big of a deal, but I couldn't figure out why I couldn't ping the hostname until I went back to the documentation.

**Comment by Mayfly277** [comment]
oups ^^, thx for the advice ;)

**Comment by bdesforges** [comment]
And maybe also adjust the driagram and corresponding png files:

- docs/diagram.drawio
- docs/img/GOAD.png
- docs/img/GOAD-Light_schema.png
- docs/img/GOAD_schema.png

**Comment by cmprmsd** [comment]
Hmm. This should be changed also in `./ad/GOAD-Light/scripts/constrained_delegation_kerb_only.ps1` right?
This typo is all over the place according to "grep -iR" :sweat_smile: 

The scripts will fail due to this change.

**Comment by Mayfly277** [comment]
yes i rollback the change and also i will not fix this issue i guess (change in blogpost, scripts, etc...) ^^
