### ISSUE TITLE
Several errors during installation

### ISSUE THREAD

**Issue by ncrnkr** [Orange-Cyberdefense/GOAD#283]
Hello everyone

I just installed VMWare and Vagrant+Entitys today.

During vagrant up I get the following errors:

> C:\Users\Nico\Documents\GOAD-main\ad\GOAD-Light\providers\vmware>vagrant up
> 
> Bringing machine 'GOAD-DC01' up with 'vmware_desktop' provider...
> Bringing machine 'GOAD-DC02' up with 'vmware_desktop' provider...
> Bringing machine 'GOAD-SRV02' up with 'vmware_desktop' provider...
> ==> GOAD-DC01: Box 'StefanScherer/windows_2019' could not be found. Attempting to find and install...
>     GOAD-DC01: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
>     GOAD-DC01: Box Version: 2021.05.15
> C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:163:in `rescue in execute': Zugriff verweigert (5) (Vagrant::Util::Subprocess::LaunchError)
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:156:in `execute'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:25:in `execute'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:212:in `block in execute_curl'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:211:in `execute_curl'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:165:in `head'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:615:in `metadata_url?'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:108:in `block in call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:106:in `map'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:106:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:87:in `handle_box'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:45:in `block in call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `synchronize'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/call.rb:56:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/check_vmware.rb:26:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/fix_old_machine_id.rb:27:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/config_validate.rb:28:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/compatibility.rb:34:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:247:in `action_raw'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:216:in `block in action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:649:in `lock'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/batch_action.rb:89:in `block (2 levels) in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
> C:/Program Files/Vagrant/embedded/gems/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:89:in `create_process': Zugriff verweigert (5) (ChildProcess::LaunchError)
>         from C:/Program Files/Vagrant/embedded/gems/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:34:in `start'
>         from C:/Program Files/Vagrant/embedded/gems/gems/childprocess-4.1.0/lib/childprocess/windows/process.rb:70:in `launch_process'
>         from C:/Program Files/Vagrant/embedded/gems/gems/childprocess-4.1.0/lib/childprocess/abstract_process.rb:81:in `start'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:158:in `block in execute'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/safe_chdir.rb:29:in `block (2 levels) in safe_chdir'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/safe_chdir.rb:28:in `chdir'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/safe_chdir.rb:28:in `block in safe_chdir'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/safe_chdir.rb:27:in `synchronize'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/safe_chdir.rb:27:in `safe_chdir'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:157:in `execute'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/subprocess.rb:25:in `execute'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:212:in `block in execute_curl'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:211:in `execute_curl'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/downloader.rb:165:in `head'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:615:in `metadata_url?'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:108:in `block in call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:106:in `map'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:106:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:87:in `handle_box'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:45:in `block in call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `synchronize'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/call.rb:56:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/check_vmware.rb:26:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/fix_old_machine_id.rb:27:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/config_validate.rb:28:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Users/Nico-MarcelRinker/.vagrant.d/gems/3.1.4/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/action/compatibility.rb:34:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:247:in `action_raw'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:216:in `block in action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:649:in `lock'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `call'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `action'
>         from C:/Program Files/Vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/batch_action.rb:89:in `block (2 levels) in run'
>         from C:/Program Files/Vagrant/embedded/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

It can't find the boxes in the Vagrant Cloud. I thought it might be due to my PiHole, but unfortunately deactivating it didn't help either.

Do you have any ideas?

**Comment by Mayfly277** [comment]
sorry this sound like a vagrant issue and not a goad issue.
also this look like that : https://github.com/hashicorp/vagrant/issues/5869
