### ISSUE TITLE
NHA -  permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by daviosardinha** [Orange-Cyberdefense/GOAD#285]
Hi there.
There is an issue when trying to execute `./goad_docker.sh` script without using sudo command.
if **./goad_docker.sh** script is executed alone, script is able to see that current user is not part of Docker group and requests for credentials, but it seems like even tho you put the password, it is not used later on to execute Docker and the script fails.

It only works if we execute the script with sudo: `sudo ./goad_docker.sh`
![2024-10-21_23-42](https://github.com/user-attachments/assets/37dbd035-1e22-48eb-a06f-07b8f7c57a6f)

**Comment by Mayfly277** [comment]
ok should be fixed now ;)
