### ISSUE TITLE
Feature Request: Automatically Install Elastic Endpoint Detection and Response (EDR)

### ISSUE THREAD

**Issue by Sandstone3310** [Orange-Cyberdefense/GOAD#286]
Hi,

Amazing work firstly my friend. It would be amazing to see Elastic EDR auto install on all GOAD machines to practice evasion, detection and response.

**Comment by Mayfly277** [comment]
ok to install it with the rest during the global install process: 
```
> set_lab <yourlab>
> set_iprange <your iprange>
> set_provider <your provider>
```

and than you could add a list of extension to enable directly on install (separate by a space)
```
>set_extension elk
```

have fun ;)
