### ISSUE TITLE
VBoxManage Vagrant - Virtualbox docker install

### ISSUE THREAD

**Issue by WiseS0cks** [Orange-Cyberdefense/GOAD#291]
Running freshly pulled kali image on proxmox and using virtualbox for the AD setup. Updated and upgraded distro prior to installing. Have also tried running with sudo and same issue. 

uname -r : 6.11.2-amd64

![GOAD1](https://github.com/user-attachments/assets/e312b71e-464c-45d4-a1f4-e7d4a3cd8a8c)

![GOAD2](https://github.com/user-attachments/assets/ea89b116-e186-481c-815d-997f01337964)

**Comment by WiseS0cks** [comment]
Here is my proxmox config 
![config](https://github.com/user-attachments/assets/0978d497-0707-415a-9ddb-a7eedbefa9e2)

**Comment by Mayfly277** [comment]
Nested virtualisation is not a good idea and you should avoid doing that (really too slow).
Also this is a vagrant issue no goad, i think it is due to options in your proxmox, may be look in proxmox doc to see if you can find the issue : https://pve.proxmox.com/wiki/Nested_Virtualization
