### ISSUE TITLE
Issue on DC-02 Installing ActiveDirectoryDSC Module fail. 

### ISSUE THREAD

**Issue by PyaeSonePhyoThu** [Orange-Cyberdefense/GOAD#293]
TASK [child_domain : Install XactiveDirectory] ****************************************************
fatal: [dc02]: FAILED! => {"changed": false, "msg": "Problems installing ActiveDirectoryDSC module: Package 'ActiveDirectoryDsc' failed to download.", "nuget_changed": false, "output": "", "repository_changed": false}  

I got this error while I run `ansible-playbook -i ../ad/GOAD-Light/data/inventory -i ../ad/GOAD-Light/providers/vmware/inventory main.yml` this command on my kali VM.

How can I fix this issue. Thanks

**Comment by Mayfly277** [comment]
The vm is not connected to internet.
This package is the first downloaded in the list so this is why you get this issue on that

**Comment by N4iF** [comment]
WHAT IS THE SOLUTION FOR THIS ERROR. I tried to change the network configuration in the virtualbox or editing the vagrantfile but not working either. I cannot ping google.com from the boxes and I get ActiveDirectoryDSC error

**Comment by N4iF** [comment]
The DNS asking it self in 127.0.0.1 causing loop for the configuration in the adapter try to add alternative IP 8.8.8.8 in the ncpa.cpl page. must probably the problem in DNS
