### ISSUE TITLE
Golden ticket with external forest not working

### ISSUE THREAD

**Issue by Monishborvankar** [Orange-Cyberdefense/GOAD#297]
hello! i'm trying Golden ticket with external forest done every proceess got SID's and dragon.ccache but moving forward encounterd following error , pls help
![image](https://github.com/user-attachments/assets/9fae76ee-f27b-4ffb-acce-1b5bc3bb0e23)

![image](https://github.com/user-attachments/assets/42a6d83c-386d-44bb-b43b-0b9a109fc713)

thank you

**Comment by michiiii** [comment]
seems to me like the extra sids you are using does not make sense. because you are using a domain sid and not an object sid. 
if you want to be DA in the other domain you gotta add a -512 to the extra SID.
