### ISSUE TITLE
What's the easiest way to add a DC with Windows Server 2022 (Proxmox)?

### ISSUE THREAD

**Issue by YugoCode** [Orange-Cyberdefense/GOAD#299]
I have a fully configured lab environment running on Proxmox, and everything is working smoothly. However, I now need to perform dedicated testing on Windows Server 2022.

What would be the most straightforward way to add a new Domain Controller running Windows Server 2022? Additionally, would it make sense to integrate this as an option in the build script to streamline adding a Windows Server 2022 DC when needed?

Thank you for any guidance! 😊

**Comment by Mayfly277** [comment]
you should look at ludus template, they got the packer receipe to build a windows server 2022 :)
