### ISSUE TITLE
License

### ISSUE THREAD

**Issue by StevenDias33** [Orange-Cyberdefense/GOAD#3]
Hi, what is the license to this project ? can i fork-it to modify it and add a terraform deployment ?

**Comment by Mayfly277** [comment]
Hi, yes i forgot to add a licence, but it's free to use don't worry.
We will add a GPL licence.
About terraform, i have done Packer and Terraform playbooks for Proxmox.
I think i will release those since i clean-up the code.

**Comment by StevenDias33** [comment]
Ok thanks for your answer :)
