### ISSUE TITLE
parameter name 'AcceptLicense'

### ISSUE THREAD

**Issue by NA3** [Orange-Cyberdefense/GOAD#30]
```
TASK [common : Windows | Check for ComputerManagementDsc Powershell module] ***********************************************************************************************************************************************************************************************************************************************
fatal: [192.168.56.12]: FAILED! => {"changed": true, "msg": "Problems installing ComputerManagementDsc module: A parameter cannot be found that matches parameter name 'AcceptLicense'.", "nuget_changed": true, "output": "", "repository_changed": false}
fatal: [192.168.56.23]: FAILED! => {"changed": true, "msg": "Problems installing ComputerManagementDsc module: A parameter cannot be found that matches parameter name 'AcceptLicense'.", "nuget_changed": true, "output": "", "repository_changed": false}
fatal: [192.168.56.22]: FAILED! => {"changed": true, "msg": "Problems installing ComputerManagementDsc module: A parameter cannot be found that matches parameter name 'AcceptLicense'.", "nuget_changed": true, "output": "", "repository_changed": false}
fatal: [192.168.56.10]: FAILED! => {"changed": true, "msg": "Problems installing ComputerManagementDsc module: A parameter cannot be found that matches parameter name 'AcceptLicense'.", "nuget_changed": true, "output": "", "repository_changed": false}
fatal: [192.168.56.11]: FAILED! => {"changed": true, "msg": "Problems installing ComputerManagementDsc module: A parameter cannot be found that matches parameter name 'AcceptLicense'.", "nuget_changed": true, "output": "", "repository_changed": false}
```

![image](https://user-images.githubusercontent.com/3059879/184222369-58c31299-2566-4a6a-b46a-e74119bf9cdb.png)

is like community.windows galaxy don't work as execpt
i have install this module on dc1 and got this after:

![image](https://user-images.githubusercontent.com/3059879/184222587-6af42fc9-9ee0-42f1-b1e1-4af5ccc1f100.png)

![image](https://user-images.githubusercontent.com/3059879/184222759-03621f12-2f6f-44e5-b975-c83f8d05702a.png)

if someone can help me to pass this error, thanks in advance

**Comment by NA3** [comment]
got it workoning after folowing this post:
[](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2)
```
Install-PackageProvider -Name NuGet -Force
Install-Module PowerShellGet -AllowClobber -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
```
someone can help me to add thins on the ansible playbook please, is my first time using this tool?
Regards.

**Comment by Mayfly277** [comment]
thx for your contribution on your install without elk.
about elk and chocolatey i will look at it and retry as soon as i can.

**Comment by strayge** [comment]
workaround - downgrade `community.windows`:
```sh
ansible-galaxy collection install community.windows:==1.10.0
```

**Comment by Mayfly277** [comment]
Ok i made a PR here  #46 to fix this.
The accept license is due to an option added on community.windows 1.11, but this option is not compatible with PowerShellGet installed by default on the vm. So the playbook now upgrade PowerShellGet and then launch the rest of the actions.
