### ISSUE TITLE
GOADv3 Ansible-Galaxy Community.General Issue

### ISSUE THREAD

**Issue by surgicalmittens** [Orange-Cyberdefense/GOAD#302]
Hi, 

When I run `./goad.sh -p ludus` on my ludus server I get an error.

The `check` command produces the following output. 
`[*] User is admin     : True

[+] ansible-playbook found in PATH

[+] Ansible galaxy collection ansible.windows is installed

[-] Missing ansible-galaxy collection community.general

[+] Ansible galaxy collection community.windows is installed`

I've tried manually switching to the venv and running this command.
`ansible-galaxy collection install community.general`

I was able to install the `ansible.windows` and `community.windows` collections that way. However community.general doesn't work.

Thanks.

**Comment by Mayfly277** [comment]
look like a venv creation issue during install. i changed the way venv is checked last week so should be good now ;)
