### ISSUE TITLE
Vagrant VMware Utility issue with WSL

### ISSUE THREAD

**Issue by Sztaklero** [Orange-Cyberdefense/GOAD#308]
After installing everything according to the instructions for Windows—VMware plus WSL—when I try to install, I get this error. What could be the problem? Everyone has permissions for this folder. I’ve tried reinstalling it again, but it still doesn’t work.

![lol](https://github.com/user-attachments/assets/a66c92b0-1de5-41df-81be-d41a70a54f7a)

GOAD/vmware/local/192.168.56.X (28f18f-goad-vmware) > check
[+] vagrant.exe found in PATH
[-] not enough ram on the system
[+] ansible-playbook found in PATH
[+] Ansible galaxy collection ansible.windows is installed
[+] Ansible galaxy collection community.general is installed
[+] Ansible galaxy collection community.windows is installed
[+] vagrant plugin vagrant-reload is installed
[+] File /mnt/c/Program Files (x86)/VMware/VMware Workstation/vmrun.exe present in the file system
[+] vagrant plugin vagrant-vmware-desktop is installed

GOAD/vmware/local/192.168.56.X (28f18f-goad-vmware) > install
[*] Launch providing
[*] CWD: /workspace/28f18f-goad-vmware/provider
[*] Running command : vagrant.exe up
Vagrant encountered an error while attempting to load the utility
service key file. This error can occur if the Vagrant VMware Utility
has not yet been installed, or if it was installed incorrectly. If
this error persists after running the Vagrant VMware Utility installer
again, please open a new issue at:

  https://github.com/hashicorp/vagrant-vmware-desktop/issues

Information about the Vagrant VMware Utility, including installation
instruction, can be found here:

  https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html

  Path:  /mnt/c/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-utility.client.crt
  Error: Permission denied @ rb_sysopen - /mnt/c/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-utility.client.crt
[-] Providing error stop

GOAD/vmware/local/192.168.56.X (28f18f-goad-vmware) >

**Comment by Mayfly277** [comment]
Hum maybe i forgot to check the installation of vmware utility in the check.
Please install : https://developer.hashicorp.com/vagrant/install/vmware

**Comment by tylertank** [comment]
I am also getting this same error with vmware utility installed.

**Comment by Mayfly277** [comment]
can you check permission on the file :  /mnt/c/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-utility.client.crt ?

**Comment by Sztaklero** [comment]
i installed everything but wont work, but after go for virtualbox, everything works perfect, we can close this one thanks guys
