### ISSUE TITLE
fatal: [dc01]: UNREACHABLE! => {"changed": false, "msg": "ssl: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))", "unreachable": true}

### ISSUE THREAD

**Issue by sandsoncosta** [Orange-Cyberdefense/GOAD#324]
I entered each VM and included the ping permission in the FW.
I'm getting this fatal every time.
What could it be?
![image](https://github.com/user-attachments/assets/d941873a-77bf-452f-ad19-5d6313aae25d)

**Comment by sandsoncosta** [comment]
I trying VirtualBox now.

**Comment by sandsoncosta** [comment]
I managed to install the entire lab via virtualbox + Ubuntu

**Comment by nothinguntil** [comment]
I am running into the same issue using virtualbox and kali.  was there a resolution to this?
