### ISSUE TITLE
fatal: [dc02]: UNREACHABLE! => {"changed": false, "msg": "winrm connection error: HTTPSConnectionPool(host='192.168.56.11', port=5986): Read timed out. (read timeout=500)", "unreachable": true}

### ISSUE THREAD

**Issue by sandsoncosta** [Orange-Cyberdefense/GOAD#325]
If I increase the timeout, will it work?
What would it be like?

**Comment by sandsoncosta** [comment]
![image](https://github.com/user-attachments/assets/6ff3c470-ba3b-4148-94df-3b0b4de71f9d)

**Comment by sandsoncosta** [comment]
I managed to install the entire lab via virtualbox + Ubuntu

**Comment by Chemsse57** [comment]
Hello how did you solve it ? I've got the same error
