### ISSUE TITLE
TASK [mssql : Install the database][goad lab]

### ISSUE THREAD

**Issue by sandsoncosta** [Orange-Cyberdefense/GOAD#331]
The database was installed on SRV02 and SRV03.
SRV03 does not have Management Studio. Is this what is expected from the lab?
SRV02 did not install the database that is in the GOAD/ad/NHA/files/SQL/academy_dump.sql folder. Should it be installed?
![image](https://github.com/user-attachments/assets/0ed63aa1-9768-44a4-a204-f3afec869c68)

**Comment by Mayfly277** [comment]
"SRV03 does not have Management Studio. Is this what is expected from the lab?" 
=> yes there is some trouble in mssql management studio on srv03 so i removed it long time ago.

" SRV02 did not install the database that is in the GOAD/ad/NHA/files/SQL/academy_dump.sql folder. Should it be installed?"
=> why do you want a db of nha lab installed on goad lab ?
