### ISSUE TITLE
Bloodhound timeout & Responder not getting any connections

### ISSUE THREAD

**Issue by KenjiEndo15** [Orange-Cyberdefense/GOAD#36]
Hello !

## BloodHound

I'm using my own host to launch the BloodHound ingestor on Linux (using Exegol as you do in your [guide](https://mayfly277.github.io/posts/GOADv2-pwning-part3/)).
It works fine for the following command:
```
bloodhound.py --zip -c All -d north.sevenkingdoms.local -u brandon.stark -p iseedeadpeople -dc winterfell.north.sevenkingdoms.local
```

However, for the 2 next following commands I get a "Connection timed out", even though it finds the domain.
```
bloodhound.py --zip -c All -d sevenkingdoms.local -u brandon.stark@north.sevenkingdoms.local -p iseedeadpeople -dc kingslanding.sevenkingdoms.local
```
```
bloodhound.py --zip -c All -d essos.local -u brandon.stark@north.sevenkingdoms.local -p iseedeadpeople -dc meereen.essos.local
```

My guess is that LDAP connection fails for whatever reason. But why would it work for the first command?

**Edit** : 
I've done a lot of troubleshooting and everything with Ldap3 works fine. 
The Windows ingestor used (directly on the machines) works fine as well. 
So my guess is the BloodHound linux ingestor (bloodhound.py) struggles with some things related to vagrant + virtualbox...

## Responder

~~Still following your guide, I noticed that I didn't get any connection on Responder (even when I attempt coerced authentications).~~
~~Before the question comes, I put the right interface name and IP :+1:~~

~~Is there any troubleshoot steps I should take to know what is the problem here?~~

**Fix**: I had a firewall activated that was blocking incoming connections for Responder. I'm still troubleshooting for BloodHound but with no success for now.

Thank you in advance!

**Comment by Mayfly277** [comment]
Did you setup your /etc/hosts well ? Did you get the last bloodhound.py version ? Can you give the log with -v ?
As it is not an issue on the lab (as the windows ingestor work well) i close the issue.
Feel free to reopen if it is due to an error on the lab :)
