### ISSUE TITLE
Nested Virtualization

### ISSUE THREAD

**Issue by pkyria14** [Orange-Cyberdefense/GOAD#38]
Setup : Windows 10 machine - host , with virtualbox installed
                                                - VirtualBox with Ubuntu 22 guest trying to clone and setup project
                                                    - error after running "vagrant up"
![ERROR](https://user-images.githubusercontent.com/35496298/189692706-697f2036-e5fe-41c7-abca-9ad3cf7e87b4.PNG)

After a lot of troubleshooting : i disabled the hyperv in my windows host and enabled nested virtualization on virtualbox. 
I also have vmware and i read somewere it might not play nice with the resources with virtualbox.
Any ideas?

**Comment by ZelliBigED** [comment]
Hello Together,

Also tried nested virtualization.
There are some caveeats, cause of same resources usage from host machine.
Tried with proxmox, debian vm and virtualbox on debian and also aczmtualy
trying on VMware esxi 7.0 u3.

Better way is only deploy the machines via vagrant, next step is exporting
them as appliance or single vm and afterwards import it directly on
batemetal Hypervisor.

Windows 11 native with virtualbox also works provisioning with Windows wls
and ansible possible.

My difficulties actually are performance issues on host system, 2 TB nvme
SSD installed on howt but in virtualbox vms there are read write speeds
very low on disk. Trying to get a solution, if I create a vm disk on
virtualbox speeds are OK 1.5-3.5GB/s
But on Windows vm and Linux vm only writes and reads up to 100MB/s sometime
only 400-700KB/s.

Anyoone an idea?

Greets THX for GOAD lab great to play with Ride on.

pkyriakou ***@***.***> schrieb am Mo., 12. Sept. 2022, 17:23:

**Comment by lkarlslund** [comment]
Nested virtualization with Virtualbox *sucks* so hard, that nothing works. Try VMware Workstation Player 16.0 - if your host is running Windows 10/11 I have a description on how/what to do at https://github.com/lkarlslund/deploy-goad
