### ISSUE TITLE
[Suggestion] Turn on WebClient service on Braavos

### ISSUE THREAD

**Issue by skorov** [Orange-Cyberdefense/GOAD#43]
This lab is awesome! I've been playing around with it for a bit now.

It would be great for people to try the WebDAV coerced auth trick somewhere in the lab. E.g.
`./Coercer.py -wh hackerbox -t braavos -u <essos_user> -p <user_pass>`

By default this will not work. The target must have the WebClient service enabled. This service does not exist by default on Windows Servers, so to get it, we'd need to add the WebDAV Redirector role/feature. We then set the WebClient service to start on boot.

Performing this coerced auth with would tie in nicely to the RBCD attack again Meereen & Braavos.

Keen to hear your thoughts. 🙂

**Comment by Mayfly277** [comment]
Hello, i totally agree with your suggestion ! it is the next feature on the todo list :)

**Comment by Mayfly277** [comment]
this was done a long time ago i forgot to close that.
