### ISSUE TITLE
DC02 - FAILED - RETRYING: [192.168.56.11]: Create user

### ISSUE THREAD

**Issue by polmoreno** [Orange-Cyberdefense/GOAD#44]
There's an error while creating users arya.stark, eddard.stark, catelyn.stark and robb.stark.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 475
failed: [192.168.56.11] (item={'key': 'arya.stark', 'value': {'firstname': 'Arya', 'surname': 'Stark',
...
"msg": "Unhandled exception while executing module: The term 'Add-Warning' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}+

Thanks in advanced.

**Comment by Mayfly277** [comment]
Are you sure your server is well up during this part ? not in a reboot state unfinished ?
If you replay the main.yml did you still got the issue ?

**Comment by Mayfly277** [comment]
Some of my co-worker got the same issue during install, i take a look at the error ;)

**Comment by Mayfly277** [comment]
Try to connect to the 192.168.56.11 with vagrant/vagrant (in qwerty by default), and run the command : `gpupdate`
and next re-run the playbooks 
i will add this command in the playbook to avoid that kind of error.

**Comment by naksyn** [comment]
`vagrant powershell DC02 -c gpupdate` before re-running the playbook solved the issue for me.

**Comment by Mayfly277** [comment]
i made a PR to fix this here #46 it is now merged into the main branch
