### ISSUE TITLE
[Documentation question] What are GO's? 

### ISSUE THREAD

**Issue by qx-775** [Orange-Cyberdefense/GOAD#5]
in the `README.md` it says:
```plaintext
the lab take environ 60Go (but you have to get the space for the vms vagrant images windows server 2016 (6.15Go) / windows server 2019 (6.52) / ubuntu 18.04 (502M))
    the total space needed for the lab is ~80-100 Go (and more if you take snapshots)
```

Could you explain what 60**Go** and ~80-100 **Go** are? What does **Go** mean? Do you mean GB as in gigabytes?

**Edit: I see the language of the author is french as by the following sentence later in the README.md ` exchange sur kingslanding ou une autre machine ?` and the french translation of Gigabyte is GigaOctet (GO).**

Perhaps you could update the README.md to be translated correctly? Otherwise I will look forward to deploy and play this game soon.

**Comment by Mayfly277** [comment]
Sorry this is due to my bad english skills ^^'
yes it's gigabytes.
i let the issue open to remember to modify the readme

**Comment by Mayfly277** [comment]
The readme as been updated with the V2 release, i close the issue.
