### ISSUE TITLE
ansible-playbook main command errors

### ISSUE THREAD

**Issue by ll3N1GmAll** [Orange-Cyberdefense/GOAD#65]
I am getting these 2 errors in the ansible-playbook main command:

TASK [settings/hostname : Reboot if needed] ****************************************************************************************************************************************
changed: [192.168.56.12]
changed: [192.168.56.23]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Timed out waiting for last boot time check (timeout=600.0)
fatal: [192.168.56.11]: FAILED! => {"changed": true, "elapsed": 630, "msg": "Timed out waiting for last boot time check (timeout=600.0)", "rebooted": true, "unreachable": false}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Timed out waiting for last boot time check (timeout=600.0)
fatal: [192.168.56.10]: FAILED! => {"changed": true, "elapsed": 637, "msg": "Timed out waiting for last boot time check (timeout=600.0)", "rebooted": true, "unreachable": false}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Timed out waiting for last boot time check (timeout=600.0)
fatal: [192.168.56.22]: FAILED! => {"changed": true, "elapsed": 648, "msg": "Timed out waiting for last boot time check (timeout=600.0)", "rebooted": true, "unreachable": false}

TASK [mssql : Add service account to Log on as a service] **************************************************************************************************************************
fatal: [192.168.56.23]: FAILED! => {"added": [], "changed": false, "msg": "Failed to translate the account 'essos.local\sql_svc' to a SID", "removed": []}

PLAY RECAP *************************************************************************************************************************************************************************
192.168.56.10 : ok=14 changed=8 unreachable=0 failed=1 skipped=2 rescued=0 ignored=0
192.168.56.11 : ok=14 changed=8 unreachable=0 failed=1 skipped=2 rescued=0 ignored=0
192.168.56.12 : ok=30 changed=19 unreachable=0 failed=1 skipped=3 rescued=0 ignored=0
192.168.56.22 : ok=13 changed=7 unreachable=0 failed=1 skipped=2 rescued=0 ignored=0
192.168.56.23 : ok=41 changed=21 unreachable=0 failed=1 skipped=3 rescued=0 ignored=0

Is there a simple command or process I can utilize to resolve this issue?

**Comment by neon-schedule** [comment]
This solved all the errors for me:
- stop vms  `vagrant halt`
- start vms `vagrant up`
- rerun the playbook

Also halting the vms and just restarting the host machine helped.

**Comment by Mayfly277** [comment]
Timeout during install mean your vm is certainly doing some update. 
Reboot the vms, rerun main.yml and all will be good ;)
