### ISSUE TITLE
WinRM Initialization Error

### ISSUE THREAD

**Issue by iNoSec2** [Orange-Cyberdefense/GOAD#68]
I have the same issue as https://github.com/Orange-Cyberdefense/GOAD/issues/17 but i cant apply the solution whcih solved the problem as i cant downgrade vagrant to this old version and if i downgrade vagrant i must also downgrade virtualbox to an old version like 6.0. Here is the error:
![image](https://user-images.githubusercontent.com/51358868/207584714-8dd7f5a8-f2ab-4d39-a6a6-06902d4c2315.png)

**Comment by iNoSec2** [comment]
So i solved my problem by adding this 2 lines to Vagrantfile
```
  config.winrm.transport = "plaintext"
  config.winrm.basic_auth_only = true
```

**Comment by N4iF** [comment]
Which file in vagrantfile ?? that I need to add
write the path please
