### ISSUE TITLE
Add MSSQL admin ERROR -> jon.snow

### ISSUE THREAD

**Issue by Hexix23** [Orange-Cyberdefense/GOAD#69]
![Screenshot from 2022-12-15 10-36-33](https://user-images.githubusercontent.com/62616592/207824901-1353b3fb-d1af-4aad-8f1a-03f770e23dc2.png)

Hello goodies!!!

I wanted to know if you can help me to solve this error, I have tried to launch it multiple times, to restart the entire AD and nothing.

**Comment by UlisesOMG** [comment]
I have the same problem and I don't know how to fix that.

**Comment by Mayfly277** [comment]
can you try re-run the playbook ?
Does it fix the issue ?

**Comment by dembarthe** [comment]
Hi,

having the same issue, on both SQL users, third time I run the Ansible (just for this issue).

**Comment by sasaga** [comment]
Has anyone found the solution?

**Comment by rcegan** [comment]
Getting this one as well - I'm using VMWare + Vagrant on Windows and provisioning via an attached linux host (in my case, docker container running in WSL2). Running main.yml multiple times + servers.yml don't resolve the issue. I also tried logging into the affected servers and removing MSSQL and re-provisioning to no avail.

**Comment by Mayfly277** [comment]
sorry i don't get how you have this issue. I have rebuild the lab multiples times without this issue.
What you can try is uninstall mssql or drop the mssql folder and retry the playbook.
The code check if the folder exist : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ansible/roles/mssql/tasks/main.yml#L50

**Comment by rcegan** [comment]
Retried on another system and unable to recreate the issue on that host.

**Comment by ayman004** [comment]
> sorry i don't get how you have this issue. I have rebuild the lab multiples times without this issue. What you can try is uninstall mssql or drop the mssql folder and retry the playbook. The code check if the folder exist : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ansible/roles/mssql/tasks/main.yml#L50


I had the same issue, Uninstalling everything SQL related and deleting the SQL Server folder in programs files solved it for me. Once I did that, I rebooted the server and pushed the servers.yml playbook.

**Comment by xXxsomebodyoncetoldmexXx** [comment]
> > sorry i don't get how you have this issue. I have rebuild the lab multiples times without this issue. What you can try is uninstall mssql or drop the mssql folder and retry the playbook. The code check if the folder exist : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ansible/roles/mssql/tasks/main.yml#L50
> 
> I had the same issue, Uninstalling everything SQL related and deleting the SQL Server folder in programs files solved it for me. Once I did that, I rebooted the server and pushed the servers.yml playbook.

This solution work in my case. Thanks you so much.

**Comment by Bladetuab** [comment]
> > sorry i don't get how you have this issue. I have rebuild the lab multiples times without this issue. What you can try is uninstall mssql or drop the mssql folder and retry the playbook. The code check if the folder exist : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ansible/roles/mssql/tasks/main.yml#L50
> 
> I had the same issue, Uninstalling everything SQL related and deleting the SQL Server folder in programs files solved it for me. Once I did that, I rebooted the server and pushed the servers.yml playbook.

How to uninstalling everything SQL related and deleting the SQL Server folder ??

**Comment by ayman004** [comment]
> > > sorry i don't get how you have this issue. I have rebuild the lab multiples times without this issue. What you can try is uninstall mssql or drop the mssql folder and retry the playbook. The code check if the folder exist : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ansible/roles/mssql/tasks/main.yml#L50
> > 
> > 
> > I had the same issue, Uninstalling everything SQL related and deleting the SQL Server folder in programs files solved it for me. Once I did that, I rebooted the server and pushed the servers.yml playbook.
> 
> How to uninstalling everything SQL related and deleting the SQL Server folder ??

I did it manually by login into the server and removing anything related to SQL via control panel.
I removed the folder of SQL, which is located in "C:\\Program Files\\Microsoft SQL Server". Finally , I rebooted the server and pushed the servers.yml playbook.

**Comment by Bladetuab** [comment]
How can I find the credentials of each server ??

**Comment by ayman004** [comment]
Try vagrant:vagrant.
user: vagrant
password: vagrant

You can find it here : https://github.com/Orange-Cyberdefense/GOAD/tree/main/packer/vagrant/windows_VERSION.json

**Comment by amitn322** [comment]
This can be fixed by moving the tasks to add firewall rule before this task that tries to add the user account. For example, move these two tasks before the add task on `roles/mssql/tasks/main.yml`

```
- name: Firewall | Allow MSSQL through Firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Access for MSSQL (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "1433"
    Protocol: "TCP"
    Description: "Opens the listener port for MSSQL"

- name: Firewall | Allow MSSQL discover through Firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Access for MSSQL (UDP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "1434"
    Protocol: "UDP"
    Description: "Opens the discover port for MSSQL"


- name: Add MSSQL admin
  win_shell: |
    SqlCmd -E -Q "CREATE LOGIN [{{item}}] FROM WINDOWS"
    SqlCmd -E -Q "SP_ADDSRVROLEMEMBER '{{item}}','SYSADMIN'"
  become: yes
  become_method: runas
  become_user: "{{SQLSVCACCOUNT}}"
  vars:
    ansible_become_pass: "{{SQLSVCPASSWORD}}"
  loop: "{{sql_sysadmins}}"
```
