### ISSUE TITLE
All servers unreachable 

### ISSUE THREAD

**Issue by Yaakov-Vokaay** [Orange-Cyberdefense/GOAD#72]
Hey guys, who can help me with this problem? a friend of mine said that the problem of not working is because of memory, but, I don't know if that's the problem, I checked the machines and their ip is different, DC01 for example has ip 192.168.56.101
![image](https://user-images.githubusercontent.com/64228473/209848146-1cb8bd88-c1e3-4947-9a94-2949cd4d5c6f.png)

**Comment by Mayfly277** [comment]
Why the ip are differents ? did you use vagrant with virtualbox or vmware ?
if  the ip set in the ansible hosts file are the one in the vms it should be reacheable.

**Comment by haimianbaobao111** [comment]
I met the same question，but dc01，dc02，dc03 is ok
![image](https://user-images.githubusercontent.com/71240282/222021196-b39b823d-3c51-4fa0-8bcd-fd8a6372a41c.png)

**Comment by nickjonathan** [comment]
I am having the same issue - Only DC02 is being unreachable. 

TASK [Gathering Facts] ***********************************************************
ok: [srv03]
ok: [srv02]
ok: [dc01]
ok: [dc03]
fatal: [dc02]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='192.168.56.11', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0e1c21c400>, 'Connection to 192.168.56.11 timed out. (connect timeout=500)'))", "unreachable": true}


Any guidance would be appreciated.

**Comment by Miguelsastre** [comment]
I have the same problem but I think it may be because of the memory disk. I am not an expert on the subject either, has anyone been able to solve it?

**Comment by nickjonathan** [comment]
I have been looking into it and I have found it is the firewall that is causing this issue. So I logged in as a vagrant and disabled the Firewall. 

All seems to be working fine for me now.

**Comment by tinmarino** [comment]
I had the same issue, I did not install well the agrant plugins (because tried in parallel and it seems not supported). This solved it

```bash
sudo ufw disable
vagrant plugin install winrm
vagrant up
```

**Comment by gderybel** [comment]
I had this problem as well, i figured it out by doing the following steps:

1. Update inventory
- Add `ansible_winrm_transport=basic` and `ansible_port=5985` in the "; winrm connection (windows)" part

2. Running the commands in Powershell on every host that the issue:
- `Set-Item -Force WSMan:\localhost\Service\auth\Basic $true`
- `Set-Item -Force WSMan:\localhost\Service\AllowUnencrypted $true`

**Comment by Mayfly277** [comment]
https://github.com/Orange-Cyberdefense/GOAD/blob/main/docs/troubleshoot.md#ansible-persistent-unreachable-error

**Comment by nothinguntil** [comment]
mayfly's link above didn't work, looked and found the new location of the link that mayfly listed above and the fix for me was adding this to my Vagrantfile

config.winrm.transport = "plaintext"
config.winrm.basic_auth_only = true

did a vagrant up and its working great!!!
