### ISSUE TITLE
[mindmaps] find user list anonymously 

### ISSUE THREAD

**Issue by Peppy99999** [Orange-Cyberdefense/GOAD#81]
Hi,

I would like to have more information about this part of the LAB:  
https://mayfly277.github.io/posts/GOADv2-pwning-part2/

It said that it is a part done anonymously (no credential), however it is necessary to have user/password to get results for these command:

![image](https://user-images.githubusercontent.com/123523557/214461383-506aaa10-8fff-40b8-86cf-a8f53f9c9c39.png)

In your writeup, you have results without parameters user/password

![image](https://user-images.githubusercontent.com/123523557/214461487-14828667-232f-4b95-973a-e5ac022cb167.png)

In my side, I need to fill in these parameters or I don't have any results.
crackmapexec smb 192.168.1.12 -u "khal.." -p "ho.." --users

Something is missing from my side or it is not an enumeration anonymously ?

**Comment by Mayfly277** [comment]
This enumeration is anonymous on 192.168.56.11 (winterfell).
This enumeration is not anonymous on meereen or braavos.
i added the anonymous rpc enumeration vulnerability on purpose (see here : https://github.com/Orange-Cyberdefense/GOAD/blob/main/ad/sevenkingdoms.local/data/config.json#L311)  because you can find this on very old DC configurations.

**Comment by maycon** [comment]
Hi,

Neither I can enumerate the users on WINTERFELL:
![image](https://user-images.githubusercontent.com/23393919/220196416-2806d89c-9be0-4d51-bca6-359fe647bfa3.png)

But the anonymous logon seems to be enabled:
![image](https://user-images.githubusercontent.com/23393919/220196571-27bd2490-0fb1-476a-a6c2-f5e17a44604d.png)

Of course I tried passing the empty arguments:
![image](https://user-images.githubusercontent.com/23393919/220196654-59ac5647-6f6a-45be-b459-e21154f7f53e.png)

Appreciate any help.

**Comment by Mayfly277** [comment]
Hi, please reboot winterfell. I bet it will be ok after a reboot ;)

**Comment by maycon** [comment]
It works. Thank you, @Mayfly277. :-)
