### ISSUE TITLE
Reach the VMs from another machine on the network

### ISSUE THREAD

**Issue by ducstream-code** [Orange-Cyberdefense/GOAD#82]
Hello !
I have set up the lab on a Ubuntu 20.04, which is running in my house, i have my laptop on the same network, I can ping the the server hosting the VMs, but i cannot ping the VMs...
How can I do to join the lab from my laptop ? What do I have to change and where ? 
Thanks you

**Comment by Mayfly277** [comment]
Maybe you could add a linux vm on the lab network and pivot with it.
You could also expose the port 80 of winterfell on your local network and start from here.
Or you could simply add a linux vm on the lab network and do your tests from it. 
have fun :)
