### ISSUE TITLE
Boot init loop

### ISSUE THREAD

**Issue by PranaKn** [Orange-Cyberdefense/GOAD#83]
Hey, Guys. Did anyone had this issue before? 

I've seen a similar issue but with a hosting Windows machine.

My setup:

12 CPU
64 Ram
1 Tb HDD

ESXi 6.7 with Ubuntu 64 host and virtualbox

Expose hardware to guest is enabled

![50d44bfe-8dca-440a-b3fa-4f9e4aee01f2](https://user-images.githubusercontent.com/79663123/215926074-2742a4fd-c940-4ba8-aa10-807c94d39093.jpg)
![260611c0-ba17-40ea-8181-b9660985ac88](https://user-images.githubusercontent.com/79663123/215926076-aa09a411-872e-4f02-9dbc-91ae60e37a27.jpg)

The machine seems to be starting but remains in an endless loop

Appreciate insights

**Comment by RizzoMichael** [comment]
Hi I have the same problem

**Comment by Mayfly277** [comment]
Seems vagrant can't contact the vm on the local forwarded port for winrm on 55985. Did you have any security mechanism which could block this trafic ?

**Comment by Mayfly277** [comment]
did you found out why this append ?
i close because this issue is old and is due to vagrant and not goad.

**Comment by PranaKn** [comment]
Hi , Mayfly

I haven't been able to. I changed the environment to a local one, using
VMware and it's working fine.

Thanks for the follow up.

Em sáb., 25 de nov. de 2023 às 18:44, Mayfly ***@***.***>
escreveu:
