### ISSUE TITLE
MSSQL delayed start

### ISSUE THREAD

**Issue by fsacer** [Orange-Cyberdefense/GOAD#85]
I think it might be worth adding a delayed start to MSSQL services, as I've noticed those wouldn't start automatically after reboot if I didn't set that.

`sc config MSSQL"$"SQLEXPRESS start= delayed-auto`

Additionally, probably a check if SQL service is running would be good before trying to add admin users.

This can be done with the following ansible command as a quick fix:
`ansible -m win_shell -a 'sc.exe config MSSQL"$"SQLEXPRESS start= delayed-auto' mssql`

**Comment by Mayfly277** [comment]
thanks for the advice i will try to add that
