### ISSUE TITLE
VM keeps restarting

### ISSUE THREAD

**Issue by occamzrazor342** [Orange-Cyberdefense/GOAD#87]
My VM keeps restarting once I run 'Vagrant up' it starts installing the first DC01.  When it starts the DC, ansible gets to some negotiation step and then the system restarts.  When I try to run the DC from VirtualBox, it says that Windows needs to be reinstalled.  

![Screenshot_2023-02-08_21-08-38](https://user-images.githubusercontent.com/65502878/217699075-17301fd9-9928-4632-b9cb-99fa496370ab.png)
![Screenshot_2023-02-08_21-09-06](https://user-images.githubusercontent.com/65502878/217699076-5bd5ab28-7c23-4dd6-8e68-0e3dab13affe.png)
![Screenshot_2023-02-08_21-10-17](https://user-images.githubusercontent.com/65502878/217699078-e26a5770-059f-4359-aca9-9dfaad17d693.png)

**Comment by Mayfly277** [comment]
wow first time i see this error. i have no idea what could cause that.
Did you find any solution ?

**Comment by Mayfly277** [comment]
closed as no answer
