### ISSUE TITLE
国内玩家docker build报错

### ISSUE THREAD

**Issue by Maysec** [Orange-Cyberdefense/GOAD#89]
报错如下
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/53160265/220866940-dcd5b373-d3d3-4668-bbe3-f150ed5c6eca.png">
可以在dockerfile中指定pip源--index-url https://pypi.douban.com/simple
<img width="747" alt="image" src="https://user-images.githubusercontent.com/53160265/220866732-53c798ee-443b-4615-bfbc-29cc5a6949e8.png">

**Comment by Mayfly277** [comment]
![image](https://user-images.githubusercontent.com/23179648/221037240-dfae594d-52e2-48c8-ab61-2a4e4b18b1b8.png)
I don't know why you can't access pip repository but it is not an issue on the tool.
regards
