### ISSUE TITLE
DC01 Locks up on intial boot

### ISSUE THREAD

**Issue by Davewarrington** [Orange-Cyberdefense/GOAD#9]
Windows 10 OS running Virtualbox 6.1 
Running Vagrant up all appears to function as expected. 
When we reach the  part for the remote winrm section, it appears to timeout due to DC01 not booting fully.
It's difficult to demo of course over screen shot, but essentially the white spinning circle runs for a few revolutions then locks up.

I've attempted to boot this VM manually, with out any network adapter, or with the internal adapter attached only but no avail. 

Default windows firewall is enabled on the Win 10 device. 

![image](https://user-images.githubusercontent.com/16097102/177612742-3ffcf1a3-3b9c-4495-aef5-5d7ef4701d44.png)
![image](https://user-images.githubusercontent.com/16097102/177612814-ede391bb-ec17-4fe6-b923-7207fae53cea.png)

**Comment by Mayfly277** [comment]
However, you could try to launch the lab on vmware instead of virtualbox with the vmware-desktop provider 
`vagrant up --provider=vmware_desktop` but i don't know if this will work, i haven't tested it on vmware.

**Comment by Mayfly277** [comment]
To build the lab i use the StefanScherer boxes : https://app.vagrantup.com/StefanScherer, if you want the vmdk file you could download the vagrant box and un-compresses them to get the vmdk.
But in my opinion vagrant is here to automate this, download the boxes, set the IPs, play the necessary script to make it work fine for ansible.
Do this on hand will be a pain.

Have you try yo run a simple vagrant box in a separate project ? does it work ?

**Comment by MinoTauro2020** [comment]
i view that when i used vagrant automated when downloaded all the machines the script doesnt change the ip's

**Comment by Davewarrington** [comment]
Apologies all, was traveling, I tested via vmware images, and as reported, the  ip's are incorrect inside the vm's 

Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2021.05.15"
end

The base config machine did boot up ok however via vmware.. 


I'l run a few test later on, and see whats happening

**Comment by MinoTauro2020** [comment]
yes , i think that the problem

**Comment by MinoTauro2020** [comment]
can you repair it? i am very interesting in that lab

**Comment by Mayfly277** [comment]
As far as i know (i have no windows host to test), if you use vmware provider the ip are not set up automatically.
You will have to setup the vmnet network to dhcp to get the eth1 working, BUT the ip will not be the same as the one setup in the ansible lab inventory file (hosts). You will have to edit it to setup the ip given by the dhcp.
Let me know if after that you are able to do provisioning well.
