### ISSUE TITLE
SRV2 SRV3 Failed to unpackage

### ISSUE THREAD

**Issue by calex80** [Orange-Cyberdefense/GOAD#91]
There are any option to install this lab in Ubuntu?

Here is attached a screenshot. Thanks in advance.

![image](https://user-images.githubusercontent.com/58860205/222993637-c685fea9-ed57-4ce7-b95d-42a916da5711.png)

**Comment by Mayfly277** [comment]
it seems you try to deploy to vmware without the vmware utility installed : see : https://github.com/Orange-Cyberdefense/GOAD#or-install-with-vmware-workstation-aka-virtualbox-cest-no-way
