### ISSUE TITLE
Virtualbox Networking issue

### ISSUE THREAD

**Issue by calex80** [Orange-Cyberdefense/GOAD#93]
I am installing the lab in Ubuntu with vitualbox, but I am getting this error, I have created in Virtualbox a NAT configuration `Network CIDR: 192.168.56.0/24` but I have still getting same error.

Any help?

![image](https://user-images.githubusercontent.com/58860205/224837189-3150030c-9fdf-40e6-a019-f9b3d7eeb1dc.png)

**Comment by miko550** [comment]
The IP address range of your host-only network is the same as the IP address range of a bridged network. 
Try change host-only network to a different range

1. Open the VirtualBox Manager and select File > Preferences.
2. In the Preferences window, select Network.
3. Select the Host-only Networks tab.
4. Select the host-only network that is causing the conflict and click the Edit button.
5. In the Adapter tab, change the IPv4 Address to a different IP address range that does not conflict with any other network.
6. Click OK to save the changes.
7. Restart the virtual machine.

**Comment by calex80** [comment]
Still same error, I've changed the range, but is conflicting yet


![image](https://user-images.githubusercontent.com/58860205/224951612-b5fb864a-8768-4063-b20d-7737220668d0.png)

**Comment by Mayfly277** [comment]
Look on file > network manager
you should see the entry for your network.
![image](https://user-images.githubusercontent.com/23179648/233734579-3a2dc6bd-4402-4965-8f7e-bca69dd0462c.png)

If you want to change the range, change the ip in the vagrant file and in the inventory file
