### ISSUE TITLE
TASK [member_server : Add member server]

### ISSUE THREAD

**Issue by MusabBtoush** [Orange-Cyberdefense/GOAD#94]
I have the following error while running the "ansible-playbook ad-servers.yml"

fatal: [srv03]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'braavos' failed to join domain 'essos.local' from its current workgroup 'WORKGROUP' with following error message: The specified domain either does not exist or could not be contacted.", "reboot_required": false}
fatal: [srv02]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local' from its current workgroup 'WORKGROUP' with following error message: The specified domain either does not exist or could not be contacted.", "reboot_required": false}

**Comment by Mayfly277** [comment]
The servers can't join the domain controller, did you have any firewall problem ?
what environment did you use ?
Have you tried a vagrant reload and replay the ansible receipe ?

**Comment by Mayfly277** [comment]
closed as no answer
