### ISSUE TITLE
Installation on multiple computers? 

### ISSUE THREAD

**Issue by recanavar** [Orange-Cyberdefense/GOAD#99]
Hello,

Did anyone try to install the GOAD on multiple computer? For example, all DCs can be installed on a PC, and all SRVs can be installed on another PC. I have two laptops and both of them have 16 GB ram. So, I want to install it separately if possible. 

If anyone tried this scenario and done successfully, could you share it or give idea?

**Comment by Mayfly277** [comment]
The project is not design for this. Maybe you should give a try to goad-light project.
